### ISSUE TITLE
Flux point fitting - weird plot for Exponential Cut-Off Powerlaw Fit

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1838] opened 2018-09-29 08:45 UTC
I have a weird plot for the best fit of an Exponential Cut-Off Powerlaw in tutorial sed_fitting_gammacat_fermi.ipynb

See differences in cell 14:
* http://docs.gammapy.org/dev/notebooks/sed_fitting_gammacat_fermi.html
* http://nbviewer.jupyter.org/gist/Bultako/559f5ceaab00d1d3ed5a8d49836b2e45/sed_fitting_gammacat_fermi.ipynb

**Comment by cdeil** [comment] 2018-09-30 12:41
This issue appeared before: #1718 I think it was somehow version or cell execution order dependent and apparently wasn't really resolved.

Shouldn't be super-hard to debug and fix, putting this on the "Madrid" milestone.

**Comment by cdeil** [comment] 2018-11-15 18:42
I'm not able to reproduce this issue. I now get a good plot.

I note that the fit result and covariance matrix now for me, and in the output from @Bultako linked to above, and from #1718 is always the same. So the input to `result_ecpl.model.plot_error` should always be identical. So this is weird.

It could be a bug concerning where / how we update state in Gammapy, or just a bug that was in older versions of `uncertainties` or ... I don't know, nothing really seems plausible.

@Bultako - could you please try to reproduce the issue?
If you also can't, I'd suggest we just close this issue for now.
All of Gammapy is work in progress, so I think it's OK to close issues that we can't reproduce any more, even if there's a chance they are still around under some circumstances.

![screenshot 2018-11-15 at 19 33 32](https://user-images.githubusercontent.com/852409/48573714-64d00080-e90d-11e8-9213-d70a5825d014.png)

**Comment by Bultako** [comment] 2018-11-15 19:22
I still can reproduce the weird plot.

Good news is that the plot is fine with the stable conda env for gammapy v0.8, and also with a fresh env that I've created from the devel conda env yaml file. So, this should be something related with an outdated package in my specific env.

I close the issue.

**Closed** 2018-11-15 19:23 UTC
Labels: bug

**Comment by cdeil** [comment] 2018-11-15 19:33
@Bultako - If you still can reproduce the issue (or anyone re-encoutering the issue in the future) - it occurs in `result_ecpl.model.plot_error`, which calls `result_ecpl.model.evaluate_error` and probably already calling `evaluate_error` at `1 TeV` would show the incorrect flux errors that are used to draw the band.

https://github.com/gammapy/gammapy/blob/f0682510e2af35236e60d72a2c9e5a37d5e8805c/gammapy/spectrum/models.py#L112

`evaluate_error` calls `self.parameters._ufloats` which is creates an `uncertainties` object from the parameter values and the covariance matrix here:

https://github.com/gammapy/gammapy/blob/f0682510e2af35236e60d72a2c9e5a37d5e8805c/gammapy/utils/fitting/parameter.py#L356

So the debugging would have to be to figure out if for some reason the parameter values and covariance matrix passed in is bad, or if the object returned by `result_ecpl.model.parameters._ufloats` is bad, possiblly because of a bug in `uncertainties` for that version.

Closing is fine with me, I'm just leaving these notes because the issue has now appeared twice, so could come back.

**Comment by Bultako** [comment] 2018-11-15 20:43
I've found the culprit. (at least in my case)

I have installed [nbstripout](https://github.com/kynan/nbstripout) in a fresh env that produced a good plot, with `conda install -c conda-forge nbstripout`.

This has changed numpy, scipy and libgfortran packages.
I have tested after `nbstripout` install and I got again the weird plot.

```
$ conda install -c conda-forge nbstripout
Solving environment: done

## Package Plan ##

  environment location: /Users/jer/anaconda/envs/gammapy-dev

  added / updated specs: 
    - nbstripout


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-base-1.15.4          |   py36h8a80b8c_0         4.1 MB
    mkl_fft-1.0.6              |           py36_0         159 KB  conda-forge
    numpy-1.15.4               |   py36h6a91979_0          35 KB
    mkl_random-1.0.2           |           py36_0         377 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.6 MB

The following NEW packages will be INSTALLED:

    intel-openmp: 2019.0-118                                      
    mkl:          2019.0-118                                      
    mkl_fft:      1.0.6-py36_0                         conda-forge
    mkl_random:   1.0.2-py36_0                         conda-forge
    nbstripout:   0.3.3-py_0                           conda-forge
    numpy-base:   1.15.4-py36h8a80b8c_0                           

The following packages will be UPDATED:

    libgfortran:  3.0.0-1                              conda-forge --> 3.0.1-h93005f0_2     
    numpy:        1.15.4-py36_blas_openblashb06ca3d_0  conda-forge [blas_openblas] --> 1.15.4-py36h6a91979_0

The following packages will be DOWNGRADED:

    blas:         1.1-openblas                         conda-forge --> 1.0-mkl              
    scipy:        1.1.0-py36_blas_openblashb06ca3d_202 conda-forge [blas_openblas] --> 1.1.0-py36h28f7352_1 

Proceed ([y]/n)? y


Downloading and Extracting Packages
numpy-base-1.15.4    | 4.1 MB    | ##################################################################################################################################################### | 100% 
mkl_fft-1.0.6        | 159 KB    | ##################################################################################################################################################### | 100% 
numpy-1.15.4         | 35 KB     | ##################################################################################################################################################### | 100% 
mkl_random-1.0.2     | 377 KB    | ##################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by cdeil** [comment] 2018-11-15 20:58
@Bultako - OK, I'll re-open and try to reproduce the issue tomorrow.
What is the best way to get the env where you see the fail?
Can you produce an env.yml file that I could use?
Or should I try with the default `gammapy-dev.yml` and then run `conda install -c conda-forge nbstripout`?

It looks like an issue in `uncertainties` with certain `numpy` versions, if the issues comes and goes for you by changing numpy version. (I don't think scipy is involved here)

**Comment by Bultako** [comment] 2018-11-15 21:12
> What is the best way to get the env where you see the fail?

1. Edit `environment-dev.yml` with python=3.6, and also other name for your env (so it will not clash with ypur actual `gammapy-dev` env. 
2. 
```
conda env create -f environment-dev.yml
conda install -c conda-forge nbstripout
```
