### ISSUE TITLE
IndexError from SpectrumEnergyGroupMaker

### ISSUE THREAD

**Issue by robertazanin** [gammapy/gammapy#1368] opened 2018-04-10 13:43 UTC
In this example CTA DC1 analysis the SpectrumEnergyGroupMaker give an IndexError if e.g. `emax=100 TeV` is chosen (see comment in cell 23):

https://github.com/gammasky/cta-analyses/blob/bf571038b389b3eb13ce8ba81b35384ebd4b6750/dc-1-checks/hess_j1702/spectrum.ipynb

**Comment by cdeil** [comment] 2018-04-10 13:54
@robertazanin - I've edited the issue and description above. The bug must be in the energy group computation. I'll have a look at this tomorrow.

**Comment by cdeil** [comment] 2018-07-15 21:01
Should be fixed in gammapy master now, since last week (see #1493).
Please try again!
If there's still any issue with energy grouping, please re-open or file a new issue!

**Comment by cdeil** [comment] 2018-08-09 15:04
@robertazanin still has a case with an `IndexError`, see cell 32 here:

```
# TODO: this gives an IndexError. Why?
# ebounds = EnergyBounds.equal_log_spacing(0.11, 159, 5, unit = u.TeV)
```
https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/hess_j1702/1D_spectral_analysis.ipynb

@joleroi - Please have a look or assign over to me.

**Comment by joleroi** [comment] 2018-08-10 11:48
Indeed I can reproduce the error with this MWP

```
from gammapy.utils.energy import EnergyBounds
import astropy.units as u 
from gammapy.spectrum import SpectrumEnergyGroupMaker

e_reco = EnergyBounds.equal_log_spacing(0.01, 100, 72, u.TeV)
desired = EnergyBounds.equal_log_spacing(0.1, 160, 35, u.TeV)
print(desired)

class DummyObs(object): pass

obs = DummyObs
obs.e_reco = e_reco.to('keV')

seg = SpectrumEnergyGroupMaker(obs=obs)
seg.compute_groups_fixed(desired)
```

The error does not occure if I remove the conversion of ``e_reco`` to ``keV`` so it's probably a lacking unit converison somewhere and should be trivial to fix.

**Closed** 2018-08-10 11:57 UTC
Labels: bug

**Comment by joleroi** [comment] 2018-08-10 12:05
[The notebook](https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/hess_j1702/1D_spectral_analysis.ipynb) mentioned above now runs trough without problems
