### ISSUE TITLE
Cannot estimate `confidence` interval after `stat_profile` has been called

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#3398] opened 2021-06-23 15:36 UTC
**Gammapy version**
0.18.2

**Bug description**
`Fit` cannot estimate a confidence interval with `Fit.confidence(..., reoptimize=True)` after scanning the statistics profile with `Fit.stat_profile(..., reoptimize=True)`

**Expected behavior**
I think it's a legitimate request to estimate the confidence interval after one has looked at the statistics profile. 
I would say that in both cases letting the other parameters vary during the optimisation (`reoptimize=True`) gives the proper error estimation.

Since the two functions duplicate a bit each other's behaviour (though one is `minuit`-independent) wouldn't be more practical for `Fit.confidence` to return also the scanned profile - so to spare the additional call to `stat_profile`?
Or - the other way around - to return the edges of the confidence interval (for a given confidence level) in `stat_profile`?

**To Reproduce**
I post an example with flux points to make it short:
```python
from gammapy.modeling.models import PowerLawSpectralModel, SkyModel
from gammapy.estimators import FluxPoints
from gammapy.datasets import FluxPointsDataset
from gammapy.catalog import CATALOG_REGISTRY
from gammapy.modeling import Fit

catalog = CATALOG_REGISTRY.get_cls("gamma-cat")()
source = catalog["HESS J1507-622"]
# load data
flux_points = source.flux_points.to_sed_type(sed_type="dnde")
flux_points.table["dnde_err"] = 0.5 * (
    flux_points.table["dnde_errn"] + flux_points.table["dnde_errp"]
)
# define model
pwl = PowerLawSpectralModel(
    index=2, amplitude="1e-12 cm-2 s-1 TeV-1", reference="1 TeV"
)
model = SkyModel(spectral_model=pwl)
# define dataset and run fit
dataset_pwl = FluxPointsDataset(model, flux_points)
fitter = Fit([dataset_pwl])
result_pwl = fitter.run()
print(result_pwl)

# compute first the stat profile and then the confidence interval
# using in both case reoptimize=True
par = dataset_pwl.models.parameters[0]
profile = fitter.stat_profile(parameter=par, reoptimize=True)
confidence = fitter.confidence(parameter=par, reoptimize=True)
print(confidence)
```
you will get this
```shell
OptimizeResult

	backend    : minuit
	method     : minuit
	success    : True
	message    : Optimization terminated successfully.
	nfev       : 49
	total stat : 1.53

{'success': False, 'message': "Specified parameters('par_000_index') cannot be found in parameter list :['par_000_amplitude']", 'errp': nan, 'errn': nan, 'nfev': 0}
```
if in `stat_profile` you switch `reoptimize` to `False`, you get `confidence` to work
```
OptimizeResult

	backend    : minuit
	method     : minuit
	success    : True
	message    : Optimization terminated successfully.
	nfev       : 49
	total stat : 1.53

{'success': True, 'message': 'Minos terminated successfully.', 'errp': 0.1671742452557624, 'errn': 0.1476879184222834, 'nfev': 34}
```
It seems that the parameter is removed from the parameter list of the model when`Fit.stat_profile(..., reoptimize=True)` is called...

**Comment by adonath** [comment] 2021-06-23 19:09
Thanks a lot @cosimoNigro, I can reproduce and confirm this bug! 

From a quick look I think the following is happening:
- In the `stat_profile()` method if `reoptimize=True`, we call again `.optimize()`, which re-creates the `Minuit` object, with a different set of parameters (excluding the one of  interest)
- So another call to `.optimize()` in between will fix the issue like:
```pyton3
profile = fitter.stat_profile(parameter=par, reoptimize=True)
_ = fitter.optimize()
confidence = fitter.confidence(parameter=par, reoptimize=True)
```
The fix for this is actually already included in #3394. The solution is to not rely on the state of the `Minuit` object for the other methods like `.confidence()` .and `.covariance()`, but recreate the object and call into the corresponding `.hesse()` and `.minos()` methods. The reason why `.confidence()` and `.stat_profile()` are not the same method, is that for complex fits with reoptimization `.stat_profile()` can take a while to run.

**Closed** 2021-06-29 12:27 UTC
Labels: bug

**Comment by adonath** [comment] 2021-06-30 15:18
Just to confirm, after #3394 the issue is fixed. Here is the result:
```
OptimizeResult

	backend    : minuit
	method     : minuit
	success    : True
	message    : Optimization terminated successfully.
	nfev       : 47
	total stat : 1.26

{'success': True, 'message': 'Minos terminated successfully.', 'errp': 0.16890804963521383, 'errn': 0.1510599908650187, 'nfev': 42}
```

**Comment by cosimoNigro** [comment] 2021-06-30 15:28
Thanks @adonath!
