### ISSUE TITLE
test_compute_lima_on_off_image fail

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1717] opened 2018-08-20 15:50 UTC
Locally `test_compute_lima_on_off_image` fails for me in Gammapy master.

Most pixels are the same up to float noise in the 1e-8 range or something like that, but there's islands of pixels where the differences are ~ 1 positive or negative, so changing the assert tolerance won't help.

The issue might have appeared with the recent change in convolve implementation, I'm not sure.

I ran this to dump the arrays to FITS:
```
pytest -v gammapy/detect/tests/test_lima.py --pdb
(Pdb) from astropy.io import fits
(Pdb) fits.writeto('actual.fits', actual)
(Pdb) fits.writeto('desired.fits', desired)
(Pdb) fits.writeto('diff.fits', actual - desired)
```

The error log, version numbers and FITS images are here: https://github.com/cdeil/gammapy-issue-lima

Note that there's also two RuntimeWarnings that should probably be suppressed:
https://github.com/cdeil/gammapy-issue-lima/blob/b975cfbdba80d3effdc3cb2e6cdd06aad9d22b4c/error.txt#L43-L46

@adonath - Thoughts?

**Comment by cdeil** [comment] 2018-08-21 08:04
`compute_lima_image` and `compute_lima_on_off_image` currently optionally still take an `exposure` image as input, but it's completely unused. @adonath - OK if I remove that?

**Comment by adonath** [comment] 2018-08-21 08:57
@cdeil Yes, sure...

**Comment by cdeil** [comment] 2018-08-21 09:06
Done in 69e3eba4fe25ec5d3289fab5689e52b2159327ad

**Comment by adonath** [comment] 2018-08-21 09:40
Using the exact same environment as in your `version.txt`I cannot reproduce the issue, so I guess it's platform dependent? (but the Travis Mac OS build seems OK) So all in all this seems hard and time consuming to debug. Maybe just change back to non-fft convolution and see if this fixes the issue?

**Comment by cdeil** [comment] 2018-08-21 09:50
I struggled to reproduce today, but now managed to reproduce the issue in this environment:
```
conda create --name issue-1717 python=3.6 numpy==1.14.5 scipy==1.1.0 astropy==3.0.3 pytest
conda activate issue-1717
pip install regions
pytest -v gammapy/detect/tests/test_lima.py
```
@adonath - Can you try that please? And if you can't reproduce we could have a look together after lunch?

**Comment by adonath** [comment] 2018-08-21 10:54
@cdeil I just tried with the environment you suggested above and it works for me. No test fail.

**Comment by adonath** [comment] 2019-01-07 15:00
Do you still see this issue? If so I'd like to resolve it by changing the default convolution function for `compute_lima_image`...just to resolve the annoyance of having failing tests. I don't think this failing test points to any fundamental issues with scipy's `convolve_fft`. It's a widely used method...so I'm fine to close this issue, even if it's not fully understood.

**Closed** 2019-01-07 16:00 UTC
Labels: bug, tests

**Comment by adonath** [comment] 2019-01-07 16:03
I investigated a little bit and in indeed it's fft noise that causes the issue. An additional call to `np.rint()` after the convolution of the input counts image fixes it. Resolved directly in master in https://github.com/gammapy/gammapy/commit/ba658ee861379768cc410ed96ae551c3db24fe10.
