### ISSUE TITLE
DL3 IACT Format: towards the new proposal

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#955] opened 2017-03-21 14:30 UTC
In the context of adding the point-like IRFs into the fits file, @TarekHC proposes a data format with a fixed axis order for aeff and edist.
Is the GammaPy machinery robust enough to deal with a fixed axis order (that can be different from the one used for the HESS production)?

Bruno

For: @cdeil @jjlk @adonath

**Comment by adonath** [comment] 2017-03-21 14:44
I don't see any problem with that. Once the DL3 data format specification has settled, we'll have to adapt the code anyway...

**Comment by bkhelifi** [comment] 2017-03-21 16:29
It means that it is hardcoded, ie there is no way by reading some metadata to read them?

**Comment by adonath** [comment] 2017-03-21 17:49
Yes, it's hard-coded, but I think this is totally fine, because we only support one data format (unless DL3 defines something different and requires flexibility in axis orders...)

**Comment by cdeil** [comment] 2017-03-22 06:59
@adonath - This is a question that came up yesterday as we were working on the spec.

Currently the spec recommends an axis order, but doesn't require one.
That means Gammapy (and other tools) shouldn't rely on it, but be able to work with any axis order.
I'm assigning this issue to me as a reminder to implement a script that checks if that is the case for all the IRFs we support (and to fix implementation if needed).

@joleroi - We had issues with IRF axis order a year or two ago.

Do you remember what the conclusion of discussions was? I think it was that readers shouldn't rely on axis order, and writers should use the recommended order, no?

Do you know what the status in Gammapy is? To me it's not clear which IRF readers rely on fixed axis order and which (if any) can handle arbitrary axis order via the header keywords.

**Comment by joleroi** [comment] 2017-04-11 07:48
The issue we had with the axis order was https://github.com/gammasky/hess-host-analyses/issues/32

The readers for the EffectiveArea and EnergyDispersion rely on a fixed axis order, see e.g. http://docs.gammapy.org/en/latest/_modules/gammapy/irf/effective_area.html#EffectiveAreaTable2D.from_table

The axes are read in correcyly independent of their order in the fits file, but the data array is assumed to be in the 'correct' shape as defined by the DL3 spec.

**Comment by cdeil** [comment] 2017-04-11 08:03
This needs to be fixed, using a generic helper function or class in
https://github.com/gammapy/gammapy/blob/master/gammapy/utils/fits.py
to deal with FITS I/O for these multi-dimensional arrays in BINTABLEs:
http://gamma-astro-data-formats.readthedocs.io/en/latest/general/fits-arrays.html#bintable-hdu

I think reformatting to a standard axis order on read is better than always keeping the array as in the FITS file, no?

**Comment by joleroi** [comment] 2017-04-11 08:18
> I think reformatting to a standard axis order on read is better than always keeping the array as in the FITS file, no?

I agree, that's already the case for the axes, the problem is that the data need to be reshaped to the correct axis order.

**Comment by cdeil** [comment] 2018-05-03 18:02
I'm closing this old issue.

Looks like the discussion above is about work in progress in 2017 concerning IRF axis order. For this we still have #1221 open with current TODO reminder, and #1288 where prototyping on a new more general scheme was started.

The first comment also mentions point-like IRFs, and to support those out of the box definitely more work is needed, i.e. to read the energy-dependent RAD cut and to use it in analysis, and also to go into point-like or full-enclosure analysis mode depending on HDUCLAS header keys. If someone wants to start discussion and work on that feature, please open a new issue (having it mixed in with the IRF axis order discussion here form 2017 in one thread will be too confusing).

**Closed by cdeil** 2018-05-03 18:02 UTC
Labels: question
