### ISSUE TITLE
Modify MapMaker

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1899] opened 2018-11-05 16:17 UTC
I am just mentioning this issue down before implementing. `MapMaker` needs to evolve a bit as a high level user interface, so that it

- [ ] Computes edisp and psf 

- [ ] Can choose "appropriate" finely binned true energy bins.

**Comment by adonath** [comment] 2018-12-20 13:42
This is now a duplicate of #1970. As all the discussion is there, I'll close this issue. @AtreyeeS Let's continue the discussion in #1970.

**Closed by adonath** 2018-12-20 13:42 UTC
Labels: feature
