### ISSUE TITLE
SafeMaskMaker throws an error when all bins are already safe

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3437] opened 2021-07-21 15:15 UTC
**Gammapy version**

0.18.2

**Bug description**

Applyling a `SafeMaskMaker` using the `aeff-max` method crashes when the effective area is actually nowhere smaller than the given limit.

Using the MAGIC data from the open crab sample:
```
import astropy.units as u
from astropy.coordinates import SkyCoord, Angle

from regions import CircleSkyRegion

from gammapy.data import DataStore
from gammapy.datasets import Datasets, SpectrumDataset
from gammapy.makers import (
    SpectrumDatasetMaker,
    ReflectedRegionsBackgroundMaker,
    SafeMaskMaker,
)
from gammapy.maps import MapAxis, Map


e_reco_axis = MapAxis.from_energy_bounds(0.1, 5, 30, unit="TeV", name="energy")
e_true_axis = MapAxis.from_energy_bounds(0.1, 5, 10, unit="TeV", name="energy_true")

datastore = DataStore.from_dir('joint-crab/data/magic/')
observations = datastore.get_observations()

target_position = SkyCoord.from_name('Crab')
on_region_radius = Angle(observations[0].aeff.meta['RAD_MAX'], unit=u.deg)
on_region = CircleSkyRegion(center=target_position, radius=on_region_radius)

dataset_maker = SpectrumDatasetMaker(
    containment_correction=False, selection=["counts", "exposure", "edisp"]
)
bkg_maker = ReflectedRegionsBackgroundMaker()
safe_mask_masker = SafeMaskMaker(methods=["aeff-max"], aeff_percent=5)

datasets = Datasets()
for obs_id, observation in zip(observations.ids, observations):
    dataset = dataset_maker.run(
        SpectrumDataset.create(
            e_reco=e_reco_axis, e_true=e_true_axis, region=on_region,
            name=str(obs_id)
        ),
        observation
    )
    dataset_on_off = bkg_maker.run(dataset, observation)
    dataset_on_off = safe_mask_masker.run(dataset_on_off, observation)
    datasets.append(dataset_on_off)

```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-d80e55c989e4> in <module>
     15     e_reco_axis=e_reco_axis_fpe,
     16     e_true_axis=e_true_axis_fpe,
---> 17     model=model_fpe,
     18 )
     19 

<ipython-input-10-aab559fc42a5> in create_spectrum_dataset(e_reco_axis, e_true_axis, model)
     23        )
     24        dataset_on_off = bkg_maker.run(dataset, observation)
---> 25        dataset_on_off = safe_mask_masker.run(dataset_on_off, observation)
     26        dataset_on_off.models = model
     27        datasets.append(dataset_on_off)

~/.local/anaconda/envs/pyirf/lib/python3.7/site-packages/gammapy/makers/safe.py in run(self, dataset, observation)
    219 
    220         if "aeff-max" in self.methods:
--> 221             mask_safe &= self.make_mask_energy_aeff_max(dataset)
    222 
    223         if "edisp-bias" in self.methods:

~/.local/anaconda/envs/pyirf/lib/python3.7/site-packages/gammapy/makers/safe.py in make_mask_energy_aeff_max(self, dataset)
    140         )
    141         aeff_thres = (self.aeff_percent / 100) * aeff.max_area
--> 142         energy_min = aeff.find_energy(aeff_thres)
    143         return geom.energy_mask(energy_min=energy_min)
    144 

~/.local/anaconda/envs/pyirf/lib/python3.7/site-packages/gammapy/irf/effective_area.py in find_energy(self, aeff, energy_min, energy_max)
    304 
    305         aeff_spectrum = TemplateSpectralModel(energy, self.data.data)
--> 306         return aeff_spectrum.inverse(aeff, energy_min=energy_min, energy_max=energy_max)
    307 
    308 

~/.local/anaconda/envs/pyirf/lib/python3.7/site-packages/gammapy/modeling/models/spectral.py in inverse(self, value, energy_min, energy_max)
    468 
    469             energy = scipy.optimize.brentq(
--> 470                 f, energy_min.to_value(eunit), energy_max.to_value(eunit)
    471             )
    472             energies.append(energy)

~/.local/anaconda/envs/pyirf/lib/python3.7/site-packages/scipy/optimize/zeros.py in brentq(f, a, b, args, xtol, rtol, maxiter, full_output, disp)
    774     if rtol < _rtol:
    775         raise ValueError("rtol too small (%g < %g)" % (rtol, _rtol))
--> 776     r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
    777     return results_c(full_output, r)
    778 

ValueError: f(a) and f(b) must have different signs
```

**Expected behavior**

All energy bins should be considered safe, since all effective areas are larger than the threshold.

**Comment by adonath** [comment] 2021-07-21 15:17
Thanks @maxnoe! Possibly related https://github.com/gammapy/gammapy/issues/3316...

**Comment by adonath** [comment] 2021-11-12 16:43
The following example (adapted to dev version) runs trough for me, without any error:
```python3
import astropy.units as u
from astropy.coordinates import SkyCoord, Angle

from gammapy.data import DataStore
from gammapy.datasets import Datasets, SpectrumDataset
from gammapy.makers import (
    SpectrumDatasetMaker,
    ReflectedRegionsBackgroundMaker,
    SafeMaskMaker,
)
from gammapy.maps import MapAxis, Map, RegionGeom


e_reco_axis = MapAxis.from_energy_bounds(0.1, 5, 30, unit="TeV", name="energy")
e_true_axis = MapAxis.from_energy_bounds(0.1, 5, 10, unit="TeV", name="energy_true")

datastore = DataStore.from_dir("$GAMMAPY_DATA/joint-crab/dl3/magic/")
observations = datastore.get_observations([5029748], required_irf=["edisp", "aeff"])


geom = RegionGeom.create("icrs;circle(83.63, 22.02, 0.2)", axes=[e_reco_axis])

dataset_maker = SpectrumDatasetMaker(
    containment_correction=False,
    selection=["counts", "exposure", "edisp"]
)

bkg_maker = ReflectedRegionsBackgroundMaker()
safe_mask_masker = SafeMaskMaker(methods=["aeff-max"], aeff_percent=1)

datasets = Datasets()

dataset_ref = SpectrumDataset.create(geom=geom, energy_axis_true=e_true_axis)

for obs_id, observation in zip(observations.ids, observations):
    dataset = dataset_maker.run(dataset_ref.copy(name=str(obs_id)), observation)
    dataset_on_off = bkg_maker.run(dataset, observation)
    dataset_on_off = safe_mask_masker.run(dataset_on_off, observation)
    datasets.append(dataset_on_off)
```

**Comment by adonath** [comment] 2021-11-18 15:34
Because of a lack of reproducibility I'll close the issue now. @maxnoe Please try with v0.19 once it's released and reopen if the issue remains. Thanks!

**Closed by adonath** 2021-11-18 15:34 UTC
Labels: bug
