### ISSUE TITLE
selecting the number of OFF regions in the reflected regions background estimation

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#1449] opened 2018-07-02 15:34 UTC
Hello,

Would it be possible to choose arbitrarily the number of OFF regions to be used in the background estimation?
For example I would like to use only 3 OFF regions (I have to make a comparison as much similar as possible with an analysis done with another software).
I have tried to play with the `ReflectedRegionsFinder`, changing the `angle_increment` value but putting or not putting it does not change my result.
You can try to comment / uncomment the `angle_increment` line in this snippet.

```python
import matplotlib.pyplot as plt
import numpy as np
import astropy.units as u
from astropy.coordinates import SkyCoord, Angle
from regions import CircleSkyRegion
from gammapy.image import SkyImage
from gammapy.background import ReflectedRegionsFinder

pos = SkyCoord(83.633, 22.014, unit='deg')
dec_point1 = pos.dec.to('deg') - 0.4 * u.deg
center1 = SkyCoord(83.633, dec_point1, unit='deg')

radius = Angle(0.12, 'deg')
on_region = CircleSkyRegion(pos, radius)

finder = ReflectedRegionsFinder(
    region=on_region,
    center=center1,
    angle_increment=Angle('90 deg'),
    
)
finder.run()
finder.plot()
plt.show()
```
I always get the same OFF regions
![index](https://user-images.githubusercontent.com/26409711/42173043-15eec9e2-7e1e-11e8-8b50-859af9e9839a.png)

The docstrings
http://docs.gammapy.org/dev/_modules/gammapy/background/reflected.html#ReflectedRegionsBackgroundEstimator
are not very clear to me...

Thanks a lot!

**Comment by cdeil** [comment] 2018-07-29 15:10
@registerrier - Since you volunteered to do the transition to Map for the reflected region computation, I'm assigning this issue to you. Cosimo is asking how to select a given number of off regions, whether it's possible to make that possible. I think in this case it is possible, and the fact that the options don't work is probably a bug?

**Comment by registerrier** [comment] 2018-08-01 12:53
Technically the `angle_increment` parameter is used only if a region is excluded. That is you will try to find the new source at an angle changed by this value.  If it is set to 0, this will likely result in a funny problem :).

**Comment by registerrier** [comment] 2018-08-01 13:10
I can confirm you can put `finder.run()`in a infinite loop if you give it `angle_increment=0`...

I am fixing that and will add a `max_region_number` to stop reflected region extraction after the required number is reached.

**Comment by registerrier** [comment] 2018-08-01 16:02
PR #1616 should solve the issue.

Note that to change the space between two adjacent regions the relevant parameter is `min_distance`

**Comment by cdeil** [comment] 2018-08-01 17:28
Closing issue.

@cosimoNigro - See http://docs.gammapy.org/dev/background/reflected.html
(you might have to refresh once or twice to make sure your browser fetches the new page from that URL instead of showing it from browser cache)

If it's not what you need, or not clearly describe, please re-open this issue or file a new one.

**Closed by cdeil** 2018-08-01 17:28 UTC
Labels: docs, feature
