### ISSUE TITLE
Problem of fit with sherpa

### ISSUE THREAD

**Issue by jjlk** [gammapy/gammapy#1028] opened 2017-05-17 09:12 UTC
Hi @cdeil and @joleroi , 
I've got some problem to do a spectral fit with sherpa on CTA simulated data. I don't really understand why it's happening. Everything worked fine ~2 weeks ago.

Here is a small example to illustrate the problem: 
```
import astropy.units as u

from gammapy.spectrum.models import PowerLaw
from gammapy.scripts.cta_utils import CTAObservationSimulation, Target, ObservationParameters

from gammapy.scripts import CTAPerf

# observation parameters
alpha = 0.2 * u.Unit('')
livetime = 100 * u.h
emin = 0.05 * u.TeV
emax = 5. * u.TeV
obs_param = ObservationParameters(alpha=alpha,
                                  livetime=livetime,
                                  emin=emin,
                                  emax=emax)

# target
pwl = PowerLaw(amplitude=1e-11 * u.Unit('1/(s cm2 TeV)'),
               index=2.,
               reference=1. * u.TeV)
target = Target(name='bob', model=pwl)

# perf
dir_south = './CTA-Performance-South-20170323/'
perf = CTAPerf.read('$GAMMAPY_EXTRA/datasets/cta/perf_prod2/point_like_non_smoothed/South_5h.fits.gz')

# simu
obs_id = 0
simu = CTAObservationSimulation.simulate_obs(perf=perf,
                                             target=target,
                                             obs_param=obs_param,
                                             obs_id=obs_id)

# simu output
print(simu)
stats = simu.stats_table()
print(stats[['energy_min', 'energy_max', 'background', 'excess', 'sigma']])
simu.write(outdir='./', use_sherpa=True)


from sherpa.astro.datastack import DataStack
import sherpa.astro.datastack as sh
from sherpa_model import Absorption

simu_output_dir = './'
filename = simu_output_dir + 'pha_obs' + str(obs_id) + '.fits'
sh.load_data(id=obs_id, filename=filename)
sherpa_model = 'powlaw1d.pwl'
sh.set_source(obs_id, sherpa_model)
    
pwl.ampl = 1.e-12 * u.Unit('1/(s cm2 TeV)').to('1/(s cm2 keV)')
pwl.ref = 1 * u.TeV.to('keV')
pwl.gamma = 2.

sh.notice(emin.to('keV')*0.99,emax.to('keV')*1.01)
print('JLK: threshold for spectra: ({},{})'.format(emin.to('keV')*0.99,emax.to('keV')*1.01))

sh.set_stat('WStat')
sh.fit()
sh.conf()
```

which results in weird NaN values and implies problem for the fit:
```
Dataset               = 0
Method                = levmar
Statistic             = wstat
Initial fit statistic = nan
Final fit statistic   = nan at function evaluation 33
Data points           = 12
Degrees of freedom    = 10
Reduced statistic     = nan
Change in statistic   = nan
   pwl.gamma      2           
   pwl.ampl       1e-21       
```
 
Do you have any idea what could cause that? OGIP format writting or something like that?

Thanks in advance ++

**Comment by cdeil** [comment] 2017-05-19 09:38
I poked at this a bit, but didn't find the issue.

@joleroi - Favor attender!
(Julien and I don't know how alpha is supposed to be stored, and likely that's the issue ... see below)

Here's what I know:
* The simulation runs OK, results look good: https://gist.github.com/cdeil/4ccdbd47a0997bc9371431c47b55c1e6
* I write and read AEFF, EDISP, on and off counts, all look good.
* The @jjlk mentioned on Slack that fitting works if passing data directly to Sherpa (not writing it do disk). @jjlk - Please post that working example also, e.g. in a https://gist.github.com/ or notebook. For me, changing the stat to `cash` and the fit works.
* My guess is that writing the alpha information from Gammapy broke (or something changed on the Sherpa side). @joleroi - Can you add a test that writes and reads on-off data and checks that alpha comes back OK?
* There's an example here: https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_fitting_with_sherpa.ipynb But since that reads files from gammapy-extra, I guess it could be broken, and one would only see that when reproducing the files with latest Gammapy. Suggest to keep notebooks independent, and to add pytest tests.

**Comment by joleroi** [comment] 2017-05-19 10:18
Note that you can also fit the written files with gammapy by adding this to your script
```
from gammapy.spectrum import SpectrumObservation, SpectrumFit
obs = SpectrumObservation.read("pha_obs0.fits")


model = PowerLaw(index=3,
                 amplitude=5e-12 * u.Unit('cm-2 s-1 TeV-1'),
                 reference=1 * u.TeV)

fit = SpectrumFit(obs_list=obs, model=model)
fit.fit()
fit.est_errors()
print(fit.result[0])
```
It gives me

```
Fit result info
---------------
Model: PowerLaw

Parameters:

           name     value     error         unit      min  max  frozen
        --------- --------- --------- --------------- ---- ---- ------
            index 1.999e+00 2.417e-03                    0 None  False
        amplitude 9.995e-12 3.196e-14 1 / (cm2 s TeV)    0 None  False
        reference 1.000e+00 0.000e+00             TeV None None   True

Covariance:

        name/name   index   amplitude
        --------- --------- ---------
            index  5.84e-06 -3.24e-17
        amplitude -3.24e-17  1.02e-27

Statistic: 3.338 (wstat)
Fit Range: [ 0.05011873  5.01187229] TeV
```

Which are the value you input to your simulation.

___

Obviously this does not answer your question. There is not obvious problem with the files written by gammapy, see #1033 . In general, I did not find it very convenient to do sherpa fits using wstat, because I kept running into weird issues (like this one). If I have time next week I can try to find the issue in this specific case.

**Comment by joleroi** [comment] 2017-05-19 10:25
Update:
When just running the script @jjlk provided I get warnings like this

```
WARNING: the group module (from the CIAO tools package) is not installed.
Dynamic grouping functions will not be available.
WARNING:sherpa.astro.data:the group module (from the CIAO tools package) is not installed.
Dynamic grouping functions will not be available.
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
WARNING:sherpa.astro.all:failed to import sherpa.astro.xspec; XSPEC models will not be available
sherpa.astro.datastack.utils: could not import stk library. CIAO stack files and syntax will be disabled
sherpa.astro.datastack.ds: could not import stk library. CIAO stack files and syntax will be disabled
```

Is this only me, or do @jjlk and @cdeil get the same?

**Comment by jjlk** [comment] 2017-05-19 11:29
Ola @joleroi , 

> Note that you can also fit the written files with gammapy by adding this to your script
> ```
> from gammapy.spectrum import SpectrumObservation, SpectrumFit
> obs = SpectrumObservation.read("pha_obs0.fits")
> 
> 
> model = PowerLaw(index=3,
>                  amplitude=5e-12 * u.Unit('cm-2 s-1 TeV-1'),
>                  reference=1 * u.TeV)
> 
> fit = SpectrumFit(obs_list=obs, model=model)
> fit.fit()
> fit.est_errors()
> print(fit.result[0])
> ```

Yes I'm aware of that. I'm using directly the sherpa library since I do not have an easy way to deal with additive and multiplicative models with Gammapy.

> In general, I did not find it very convenient to do sherpa fits using wstat, because I kept running into weird issues (like this one).

I understand. Everything worked 2/3 weeks ago. Did someone change something in the way gammapy data are exported to OGIP format?

> Update:
> When just running the script @jjlk provided I get warnings like this
> 
> ```
> WARNING: the group module (from the CIAO tools package) is not installed.
> Dynamic grouping functions will not be available.
> WARNING:sherpa.astro.data:the group module (from the CIAO tools package) is not installed.
> Dynamic grouping functions will not be available.
> WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
> WARNING:sherpa.astro.all:failed to import sherpa.astro.xspec; XSPEC models will not be available
> sherpa.astro.datastack.utils: could not import stk library. CIAO stack files and syntax will be disabled
> sherpa.astro.datastack.ds: could not import stk library. CIAO stack files and syntax will be disabled
> ```
> 
> Is this only me, or do @jjlk and @cdeil get the same?

I do get some warnings but nothing related to group or dataskack module: 
```
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING:sherpa.image:imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
WARNING:sherpa.astro.all:failed to import sherpa.astro.xspec; XSPEC models will not be available

```

My sherpa version, which has not been updated recently), is: 
```
In [2]: import sherpa
In [3]: sherpa.__version__
Out[3]: '4.9.0'
```

**Comment by joleroi** [comment] 2017-05-31 11:31
With #1033 I get

```
Dataset               = 0
Method                = levmar
Statistic             = wstat
Initial fit statistic = 261733
Final fit statistic   = 8.75802 at function evaluation 209
Data points           = 12
Degrees of freedom    = 10
Probability [Q-value] = 0.555212
Reduced statistic     = 0.875802
Change in statistic   = 261724
   pwl.gamma      2.00161
   pwl.ampl       9.99814e-21
WARNING: parameter value pwl.ampl is at its minimum boundary 0.0
INFO:sherpa.astro.ui.utils:Dataset               = 0
Method                = levmar
Statistic             = wstat
Initial fit statistic = 261733
Final fit statistic   = 8.75802 at function evaluation 209
Data points           = 12
Degrees of freedom    = 10
Probability [Q-value] = 0.555212
Reduced statistic     = 0.875802
Change in statistic   = 261724
   pwl.gamma      2.00161
   pwl.ampl       9.99814e-21
WARNING: parameter value pwl.ampl is at its minimum boundary 0.0
```

close ?

**Comment by cdeil** [comment] 2017-05-31 11:34
Closing this now. @jjlk - Please re-open if you still get bad results after #1033 is merged.

**Closed by cdeil** 2017-05-31 11:34 UTC
Labels: bug, question
