### ISSUE TITLE
Problems in reading ParisAnalysis fits files

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1954] opened 2018-11-27 14:05 UTC
This is not technically a gammapy issue, but I think it is important to documented.
The latest developments in gammapy breaks support for `ParisAnalysis` fits files (and also `HAP-Fr-1`, see #1897 which was not merged). 

The specific problem with the `ParisAnalysis` release is that there are neither any links to the gti tables in the `hdu-index-files`, nor reference MJDs in the observation table meta info. (Note that this used to work fine till `v0.7`)

Since the problems with both `ParisAnalysis` and `HAP-Fr` fits files lie not in the general production, but in the information contained in the index files, @registerrier , @bkhelifi and I think one option is to have a small script within `gammapy` (not in the main repo, but perhaps in `gammapy-extra`?) which will make index files according to the present requirements for gammapy.

Please opine @cdeil @adonath

**Comment by AtreyeeS** [comment] 2018-11-27 14:38
For this specific case, `observation_live_time_duration()` fails because `create_gti()` cannot find any `"MJDREFI"` in the `meta`. But `o1.obs_info["LIVETIME"]` still correctly returns the livetime. So, I was wondering if might be an option to have an `error` block in `observation_time_duration()` and return `self.obs_info["LIVETIME"]` incase `self.gti` fails? And give a BIG a warning message as well...

**Comment by cdeil** [comment] 2018-11-27 14:39
My suggestions would be:

Remove support for HESS ParisAnalysis FITS production 1 from Mar 2016 in Gammapy (see [here](https://hess-confluence.desy.de/confluence/display/HESS/HESS+FITS+data#HESSFITSdata-ParisAnalysis)). As you note, it's broken anyways and not well tested, so we might as well remove  https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-crab4-pa and the tests we have to read those IRFs (https://github.com/gammapy/gammapy/search?q=hess-crab4-pa&unscoped_q=hess-crab4-pa). Probably keep the King PSF as an example file.
I don't think it's really useful to keep, the old FITS production can never be used for a HESS publication. If you're trying to use those, IMO you're just wasting your time. If / when someone picks up the task of ParisAnalysis FITS productions again, we'll make sure it's supported by Gammapy.

Concerning the question whether to have code in Gammapy to make index files: maybe.
We do have an example in https://docs.gammapy.org/0.8/notebooks/background_model.html#Index-tables and as stated in #1597 I do think we should have a separate tutorial for that. Another example is in https://github.com/gammasky/cta-dc/blob/master/data/cta_1dc_make_data_index_files.py and there's also e.g. the HAP-HD FITS exporter and in HAP-FR you probably have one as well. I think I even tried with @JouvinLea when we wrote the first HAP-HD and HAP-FR batch exporters to share that part of the code. But in the end everyone needed something slightly different and it just wasn't possible to have a class in Gammapy that fits all use cases. The problem is that often the DL3 files without index files just don't have the information e.g. which background model belongs to which run.

So @AtreyeeS - If you want to try to write a `gammapy.data.DataStoreIndexer` (probably starting with https://github.com/gammasky/cta-dc/blob/master/data/cta_1dc_make_data_index_files.py), that could be possible, although my guess is that the main second customer (@lmohrmann using HAP-HD) would just keep using what he already has, so overall I'm not sure we should spend time on adding / reviewing that code in Gammapy. Note that if you now continue to work on HAP-FR FITS export, that is great, and it makes sense to revive the HESS FITS task group to discuss such things (especially invite @lmohrmann), and that in https://github.com/gammasky/hess-host-analyses we already have a repo where any HESS-specific scripts and codes and tests can be shared.

So @AtreyeeS @registerrier @adonath - please comment / vote on the two questions:
1. remove old PA files / tests?
2. Add `DataStoreIndexer` in Gammapy (and spend time to discuss / review the code and add tests and docs) or keep it out (e.g. in the gammapy-extra or hess-host-analyses repos) without spending any time on it?

I'm +1 to remove the PA files and 50:50 on the second task. If someone does spend time on a tutorial (#1597) they might just as well do it properly in Gammapy we tests and docs, given that even if the current format will not stay, a DL3 indexer will probably be needed. So I don't have a big concern with adding one now, only that this is low priority and we should rather work on other things. (And I'm not OK to add new code to Gammapy without review / tests / docs, that just increases work and makes it harder for us in 2019.)

**Comment by cdeil** [comment] 2018-12-03 10:06
Resolved via #1964 .

Just in case someone sees this discussion and really wants to use Gammapy with the old HESS ParisAnalysis FITS production 1: a good option is to write a Python script that applies the small fixes and reformatting for missing header keys to create a spec / Gammapy compliant version of those files. If you want to share them in HESS, just let me and @registerrier know and we'll put it on the MPIK and Lyon server and mention it on Confluence.  We actually had to do that for the HESS data release, an example of such a script is here: https://github.com/gammasky/HESS-DL3-DR1/blob/master/hess_dl3_dr1/data_release.py

IMO overall this is still a bit of a waste of time, because you'll never be able to use ParisAnalysis for HESS publications or even official cross-checks unless someone makes a new ParisAnalysis FITS production (based on reasonably new lookups and DSTs), so efforts should instead concentrate on making new FITS productions, which is what @AtreyeeS is doing for HAP-FR and @lmohrmann for HAP-HD.

**Closed by cdeil** 2018-12-03 10:06 UTC
Labels: feature, question
