### ISSUE TITLE
Documentation list for 1.0

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3143] opened 2020-11-30 14:16 UTC
As discussed in the last co-working week, I list here the action items required in gammapy 1.0 documentation effort.
Please feel free to add more items, and/or assign yourself to some particular task.

We decided to split notebooks into 

- Analysis notebooks - which do a full analysis
- API notebooks - which demonstrate a particular API.
The API notebooks need not be executed (but of course, must be tested to ensure that we do not ship broken code), so this releases some pressure on the docs-build time.

Small code examples in the rst pages will still remain.

**Major action items**

1. Have API notebook for each sub-package

- [ ] `gammapy.analysis` - notebook describing all options in HLI
- [x] `gammapy.maps`  - move `maps.ipynb` tutorial into subpage, remove code duplication in rst pages  (@QRemy)
- [x] `gammapy.makers` - notebook explain additional options not shown in current tutorials (@QRemy)
- [x] `gammapy.modeling` - move `models.ipynb`, and `modeling.ipynb` add examples for model management, use of `CompoundModels` (@AtreyeeS )
- [x] `gammapy.datasets` add general API tutorial (@QRemy)
- [ ] `gammapy.estimators` - Add API notebook
- [x] `gammapy.catalogs` - move over `catalogs.ipynb`, extend options in the notebook. (@QRemy)
- [ ] `gammapy.stats` - I find the present documentation quite good (caveat: some output cells not executed at present). I do not know if an API notebook is useful here (this is more conceptual than API based)
- [ ]  `gammapy.data`, `gammapy.irf`, `gammapy.astro`: less critical for API notebooks

2.   Add documentation for
- [x] Overview page to be updated - add a flowchart showing the Gammapy API and data levels (@adonath)
- [x] Add documentation for `RegionGeom` and `RegionNdMaps` (@LauraOlivera )
- [x] Add documentation for `FoVBackgroundMaker`
- [x] Improve documentation for stacking and handling of masks, add cross reference between existing documentation (@AtreyeeS )
- [x] Show how to use the `help()` command in more places / notebooks
- [x] Add plot for `RingBackgroundMaker` - use image from HGPS or Berge paper (@AtreyeeS)
- [x] Decide on what to do for `Dataset.plot_residuals` error bars (@AtreyeeS )
- [x] Generalise the exclusion mask tutorial to explain mask handling in general (boolean operators etc., erosion / dilation etc.), clarify conventions on inside / outside data, move it to the API tutorial section (@QRemy)
- [x] Extend maps notebook to show arithmetic operators  (@QRemy)
- [x] [Add printing valid tags to the model gallery](https://docs.gammapy.org/dev/development/howto.html#choose-a-thumbnail-and-tooltip-for-the-tutorials-gallery)
- [x] Improve IRF Theory #3290 
- [ ] Explain different between `TSMapEstimator` and `ExcessMapEstimator`
- [x] Explain difference between `MapDataset.to_spectrum()` and `MapDataset.to_spectrum_dataset` (#3367)
- [ ] Document `LabelMapAxis` and `TimeMapAxis`
- [ ] Clarify pulsar analysis tutorial

3. Add a section for user contributed notebooks (@Bultako)
- [ ] 1OnOff analysis notebook (@registerrier )
- [x] Move tutorials from Extra Topics

4. Add/link in the HowTo
- [x] Fix presently broken links
- [ ] Computing the p-value of a model

5. Fix python code present in RST pages and add these tests to the CI (@Bultako)
```
$ pytest --doctest-glob="*.rst" docs/
```
- [x] docs/getting-started.rst::getting-started.rst
- [x] docs/analysis/index.rst::index.rst
- [x] docs/data/index.rst::index.rst
- [x] docs/development/howto.rst::howto.rst
- [x] docs/development/setup.rst::setup.rst
- [x] docs/estimators/lightcurve.rst::lightcurve.rst
- [x] docs/modeling/index.rst::index.rst
- [x] docs/scripts/index.rst::index.rst
- [x] docs/stats/fit_statistics.rst::fit_statistics.rst
- [x] docs/stats/index.rst::index.rst
- [x] docs/utils/index.rst::index.rst

6. Re-structring main tutorials page layout
- [x] Remove tutorials and regroup those kept in clear categories  
- [x] Display tutorials in a gallery layout (@Bultako)

**Minor items**

- [x] `GaussianSpatialModel.to_region` - mention the number of sigmas in the region (@QRemy)
- [x] Link to older versions of the docs
- [x] #3134 
- [x] Add link to binder in tutorials page

**Comment by adonath** [comment] 2020-12-01 15:08
Thanks a lot @AtreyeeS! At first glance this looks fairly complete to me. I'll comment again if I find something is missing...

**Comment by Bultako** [comment] 2021-05-06 11:52
I have identified the following broken links in the docs:

```
[./analysis/3D/analysis_mwl.ipynb]
- Failed (404): https://arxiv.org/pdf/1905.12518.pdf.

[./api/fitting.ipynb]
- Failed (404): http://cxc.cfa.harvard.edu/sherpa/methods/index.html

[./gallery/spectral/plot_logparabola.ipynb]
- Failed (404): http://cxc.harvard.edu/sherpa/ahelp/logparabola.html_

[./development/pigs/pig-009.rst]
- Failed (404): http://www.iasf-milano.inaf.it/~giuliani/astrisim/

[./development/pigs/pig-001.rst]
- Failed (404): https://docs.scipy.org/doc/numpy-dev/neps/index.html

[./development/pigs/pig-013.rst]
- Failed (404): https://pysal.org/install
- Failed (404): https://docs.sunpy.org/en/stable/guide/installation/advanced.html

[./development/setup.rst]
- Failed (404): https://github.com/gammapy/gammapy-web
- Failed (502): https://landscape.io/github/gammapy/gammapy/master

[./development/release.rst]
- Failed (404): https://github.com/gammapy/gammapy-web

[./modeling/gallery/spectral/plot_logparabola.rst]
- Failed (404): http://cxc.harvard.edu/sherpa/ahelp/logparabola.html_

**Comment by Bultako** [comment] 2021-05-06 11:57
I paste here the python snippets provided in RST files that are not tested.

```
gammapy//catalog/hess.py:637:    >>> cat = SourceCatalogHGPS(filename) # doctest: +SKIP
gammapy//catalog/hess.py:641:    >>> source = cat['HESS J1843-033'] # doctest: +SKIP
gammapy//catalog/hess.py:642:    >>> print(source) # doctest: +SKIP
gammapy//catalog/hess.py:646:    >>> source.spectral_model().plot(source.energy_range) # doctest: +SKIP
gammapy//catalog/hess.py:647:    >>> source.spectral_model().plot_error(source.energy_range) # doctest: +SKIP
gammapy//catalog/hess.py:648:    >>> source.flux_points.plot() # doctest: +SKIP
gammapy//catalog/hess.py:653:    >>> source.components # doctest: +SKIP
gammapy//catalog/hess.py:654:    >>> cat.gaussian_component(83) # doctest: +SKIP
gammapy//utils/random/utils.py:266:    >>> from gammapy.utils.random import random_times # doctest: +SKIP
gammapy//utils/random/utils.py:268:    >>> times = random_times(size=100, rate=rate, random_state=0) # doctest: +SKIP
gammapy//utils/random/utils.py:269:    >>> times[-1] # doctest: +SKIP
gammapy//modeling/models/temporal.py:285:    >>> light_curve.evaluate(46300) # doctest: +SKIP
gammapy//modeling/models/temporal.py:290:    >>> light_curve.mean_norm_in_time_interval(46300, 46301) # doctest: +SKIP
gammapy//irf/energy_dispersion.py:43:    >>> edisp = edisp2d.to_edisp_kernel(offset='1.2 deg', e_reco=energy, energy_true=energy) # doctest: +SKIP
gammapy//irf/edisp_kernel.py:42:    >>> print(edisp) # doctest: +SKIP
gammapy//irf/edisp_kernel.py:43:    >>> edisp.peek() # doctest: +SKIP
gammapy//data/data_store.py:40:    >>> data_store.info() # doctest: +SKIP
gammapy//data/event_list.py:234:        >>> event_list = EventList.read('events.fits') # doctest: +SKIP
gammapy//data/event_list.py:236:        >>> event_list = event_list.select_energy() # doctest: +SKIP
gammapy//data/event_list.py:301:        >>> event_list = EventList.read('events.fits') # doctest: +SKIP
gammapy//data/event_list.py:303:        >>> event_list = event_list.select_parameter(parameter='PHASE', band=phase_region) # doctest: +SKIP
gammapy//data/obs_table.py:251:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:254:        ...                  time_range=Time(['2012-01-01T01:00:00', '2012-01-01T02:00:00'])) # doctest: +SKIP
gammapy//data/obs_table.py:255:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:259:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:263:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:267:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
```

Check out https://docs.gammapy.org/dev/development/howto.html#check-python-code-present-in-rst-files to make testable code snippets in the RST files.

**Comment by Bultako** [comment] 2021-05-06 12:00
Here the python code provided in docstrings of Python files that is not tested.

```
gammapy//catalog/hess.py:637:    >>> cat = SourceCatalogHGPS(filename) # doctest: +SKIP
gammapy//catalog/hess.py:641:    >>> source = cat['HESS J1843-033'] # doctest: +SKIP
gammapy//catalog/hess.py:642:    >>> print(source) # doctest: +SKIP
gammapy//catalog/hess.py:646:    >>> source.spectral_model().plot(source.energy_range) # doctest: +SKIP
gammapy//catalog/hess.py:647:    >>> source.spectral_model().plot_error(source.energy_range) # doctest: +SKIP
gammapy//catalog/hess.py:648:    >>> source.flux_points.plot() # doctest: +SKIP
gammapy//catalog/hess.py:653:    >>> source.components # doctest: +SKIP
gammapy//catalog/hess.py:654:    >>> cat.gaussian_component(83) # doctest: +SKIP
gammapy//utils/random/utils.py:266:    >>> from gammapy.utils.random import random_times # doctest: +SKIP
gammapy//utils/random/utils.py:268:    >>> times = random_times(size=100, rate=rate, random_state=0) # doctest: +SKIP
gammapy//utils/random/utils.py:269:    >>> times[-1] # doctest: +SKIP
gammapy//modeling/models/temporal.py:285:    >>> light_curve.evaluate(46300) # doctest: +SKIP
gammapy//modeling/models/temporal.py:290:    >>> light_curve.mean_norm_in_time_interval(46300, 46301) # doctest: +SKIP
gammapy//irf/energy_dispersion.py:43:    >>> edisp = edisp2d.to_edisp_kernel(offset='1.2 deg', e_reco=energy, energy_true=energy) # doctest: +SKIP
gammapy//irf/edisp_kernel.py:42:    >>> print(edisp) # doctest: +SKIP
gammapy//irf/edisp_kernel.py:43:    >>> edisp.peek() # doctest: +SKIP
gammapy//data/data_store.py:40:    >>> data_store.info() # doctest: +SKIP
gammapy//data/event_list.py:234:        >>> event_list = EventList.read('events.fits') # doctest: +SKIP
gammapy//data/event_list.py:236:        >>> event_list = event_list.select_energy() # doctest: +SKIP
gammapy//data/event_list.py:301:        >>> event_list = EventList.read('events.fits') # doctest: +SKIP
gammapy//data/event_list.py:303:        >>> event_list = event_list.select_parameter(parameter='PHASE', band=phase_region) # doctest: +SKIP
gammapy//data/obs_table.py:251:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:254:        ...                  time_range=Time(['2012-01-01T01:00:00', '2012-01-01T02:00:00'])) # doctest: +SKIP
gammapy//data/obs_table.py:255:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:259:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:263:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
gammapy//data/obs_table.py:267:        >>> selected_obs_table = obs_table.select_observations(selection) # doctest: +SKIP
```

Check out https://docs.gammapy.org/dev/development/howto.html#check-python-code-present-in-docstrings-of-python-files to make testable docstrings in the Python files.

**Comment by fabiopintore** [comment] 2021-05-06 12:23
Hi,

the link to astrisim seems no more available. I've asked to the owner if I
can restore it.
I'll let you asap.


Il giorno gio 6 mag 2021 alle ore 13:52 Jose Enrique Ruiz <
***@***.***> ha scritto:

**Comment by registerrier** [comment] 2021-05-06 12:28
> [./analysis/3D/analysis_mwl.ipynb]
> - Failed (404): https://arxiv.org/pdf/1905.12518.pdf.

 Here the issue is the `.` period at the end.

> [./api/fitting.ipynb]
> - Failed (404): http://cxc.cfa.harvard.edu/sherpa/methods/index.html
 
 Strangely this one seems to work

> [./gallery/spectral/plot_logparabola.ipynb]
> - Failed (404): http://cxc.harvard.edu/sherpa/ahelp/logparabola.html_
> 
  This one fails because of the  incorrect `_` character at the end.

> [./modeling/gallery/spectral/plot_logparabola.rst]
> - Failed (404): http://cxc.harvard.edu/sherpa/ahelp/logparabola.html_

 Same.

**Comment by fabiopintore** [comment] 2021-05-08 19:25
[./development/pigs/pig-009.rst]
- Failed (404): http://www.iasf-milano.inaf.it/~giuliani/astrisim/

The new link to AstriSIM is the following:

https://github.com/cento14/Astrisim

**Comment by AtreyeeS** [comment] 2021-12-15 17:46
I added one item to the documentation list, ie, clarification of pulsed analysis.
The current pulsar analysis notebook simply mentions that the phasing has to be done outside gammapy, but it is not totally clear how the phase information should be read by gammapy.

Maybe we can explicitly mention that a PHASE column must be added to the EVENTS file, taking care that the corresponding links to the IRFs are not broken.
Probably, showing an example (code commented out?) will be useful?

**Comment by adonath** [comment] 2022-01-05 17:29
Here is a number of small issues found by @bkhelifi:

- https://docs.gammapy.org/0.19/howto.html#access-iact-dl3-data (typo in the link)
- https://docs.gammapy.org/0.19/howto.html#extract-1d-spectra (broken link toward the tuto)
- https://docs.gammapy.org/0.19/howto.html#model-2d-images (broken link toward `2-dim sky image analysis  energy )
- https://docs.gammapy.org/0.19/howto.html#extract-a-lightcurve (broken link toward the tuto, select_time  )
- https://docs.gammapy.org/0.19/howto.html#compute-cumulative-significance : borkn link towards Datasets  info_table(cumulative=True) 
- https://docs.gammapy.org/0.19/howto.html#detect-sources-in-a-map: broken for find_peaks 
- https://docs.gammapy.org/0.19/stats/index.html#notations: broken for MapDataset
why we have ctools here : https://docs.gammapy.org/0.19/references.html#publications?
- https://docs.gammapy.org/0.19/catalog/index.html#introduction: gamma-cat is not updated since 2018... what to do about it in the future? broken link for LightCurve
- https://docs.gammapy.org/0.19/maps/index.html#getting-started: typo at the end
- https://docs.gammapy.org/0.19/maps/index.html#differential-and-integral-maps: broken link for MapAxis
- https://docs.gammapy.org/0.19/estimators/index.html#introduction: broken link towards the Li&Ma paper
- https://docs.gammapy.org/0.19/datasets/index.html#types-of-supported-datasets: we do not support HpxGeom for some datasets? broken links towards RingBackground  ReflectedBackground FluxPointDataset
- https://docs.gammapy.org/0.19/makers/reflected.html#overview: broken link towards ReflectedRegionsFinder  (the same in all the sections)
- https://docs.gammapy.org/0.19/makers/fov.html#overview: broken links towards Datasets  NormSpectralModel  PowerLaWNormSpectralModel
- https://docs.gammapy.org/0.19/data/index.html#getting-started: broken link towards EventListLAT
is binder working? for the sed_fitting, it does not

**Comment by adonath** [comment] 2022-01-07 14:03
As a reminder: `EDispKernel` and `PSFKernel` are not listed in https://docs.gammapy.org/0.19/irf/index.html#classes.

**Comment by Bultako** [comment] 2022-01-27 12:08
@bkhelifi 
I fixed most of the things of the list above in #3753 
I paste below the items that I could not fix, because I did not find the broken link or have to be fixed in another PR:

- https://docs.gammapy.org/0.19/catalog/index.html#introduction: gamma-cat is not updated since 2018... what to do about it in the future? broken link for LightCurve
- https://docs.gammapy.org/0.19/estimators/index.html#introduction: broken link towards the Li&Ma paper
- https://docs.gammapy.org/0.19/datasets/index.html#types-of-supported-datasets: we do not support HpxGeom for some datasets?
- https://docs.gammapy.org/0.19/data/index.html#getting-started: broken link towards EventListLAT
- is binder working? for the sed_fitting, it does not
- broken links towards NormSpectralModel 

There is also a broken link to a paper that I could not fix because I don't know which paper it is.
- https://ui.adsabs.harvard.edu/abs/2011JCAP...03..051

**Comment by adonath** [comment] 2022-10-14 14:05
Broken links are fixed but now. For the Estimator notebook we have different issue #3716. I'll close this issue now.

**Closed by adonath** 2022-10-14 14:05 UTC
Labels: docs, priority-high
