### ISSUE TITLE
3D (Fermi) + 1D (LST/MAGIC PointSkyRegion-style) analysis. Global fit ignores the 1D. 

### ISSUE THREAD

**Issue by mireianievas** [gammapy/gammapy#4117] opened 2022-09-29 10:48 UTC
**Gammapy version**
0.20.1

Are you using the latest stable version of Gammapy? (see https://gammapy.org/news.html)
yes

**Bug description**
Issue discussed already in slack (and I should probably have opened this ticket back then, my bad). A 3D (e.g. Fermi) and a 1D ON/OFF datasets (PointSkyRegion type, e.g. LST or MAGIC) are analyzed together with N skymodels for the 3D (with spatial and spectral components, including those for the source of interest) and 1 skymodel (the same model as in the 3D for ONLY the source of interest, including spectral and spatial components). The result, after the likelihood fit, is that one of the datasets is completely ignored in the fit. However, no error or warning is raised, so I have no idea how to debug it. 

<img width="730" alt="Captura de Pantalla 2022-09-29 a las 11 35 47" src="https://user-images.githubusercontent.com/2607760/193009687-d5d1bee3-9a8e-4fa0-852e-d625918a63cd.png">

Partial workaround: 
1) define a skymodel for the 1D dataset consisting only on a spectral component, no spatial ones. 
2) The parameters of the spectral components are linked/fixed to the corresponding spectral component of the source model in the 3D dataset (lets call the source name in the 3D dataset XXX). 
3) The source name of the skymodel then needs to be different, e.g. renamed to XXX-2, otherwise gammapy returns an error saying that the names should be unique.
4) perform the fit, and then voila both datasets contribute to the result, the confidence band is much narrower.

<img width="738" alt="Captura de Pantalla 2022-09-29 a las 11 35 57" src="https://user-images.githubusercontent.com/2607760/193009783-7fc169bf-0e19-4e89-887f-4b8cd6335b7f.png">

However, this is not a perfect solution, because the FluxPointEstimator needs to be called for each dataset with their unique source names (even when it is the same source and both datasets should contribute to the energy ranges where both instruments are sensitive). So you have Fermi points on one hand and IACT points on the other. At the overlapping energy range (~20-300 GeV)  you may have 'duplicated' points with larger error bars (because only one dataset contributes at a time). 

**Expected behavior**

The first option, i.e. defining 'datasets' to include both the 3D and the 1D (PointSkyRegion) and then making the fit should work fine, with the only difference with respect to a 3D that for the 1D model the spatial component should not contribute to the likelihood. Or if there is any reason why it shouldn't, it should at least raise an error instead of silently ignoring one of the datasets.

Another possible solution would be to try to get the FluxPointEstimation to also use the two datasets to compute each flux point, but that would involve dealing with two datasets with a source with different names in each. If the global fit works this way, no reason why the flux point estimation proceedure, which basically re-optimizes the 'norm' in each bin, shouldn't. But it sounds more 'hacky' to me than just fixing the first option and allowing the minimizer to work with this 1D+3D datasets

**To Reproduce**
1) Build a 3D dataset (suggested from a Fermi analysis done with the Fermitools).
2) Build a 1D dataset (energy-dependent / PointSkyRegion style, I ignore if the standard CircleSkyRegion analysis reproduces the issue)
3) Assign all the spatial+spectral skymodels for each source in the field of the 3D dataset.
4) Assign the spatial+spectral for the source of interest to match the one in the 3D dataset. 
5) Build the datasets([1D,3D]) object.
6) Make the likelihood fit with the models

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment] 2022-09-29 12:58
Thanks @mireianievas! I looked into this issue a while ago and found it was essentially related to the behavior of `PointSkyRegion.contains()` (https://github.com/astropy/regions/issues/474). Have you checked that the issue is still present in the current dev version?

**Comment by mireianievas** [comment] 2022-09-30 11:49
You mean the dev version of astropy?

I will try asap :)

**Comment by mireianievas** [comment] 2022-09-30 12:00
In regions/shapes/point.py I see the following bit of code

```
    def contains(self, pixcoord):
        if pixcoord.isscalar:
            in_reg = False
        else:
            in_reg = np.zeros(pixcoord.x.shape, dtype=bool)

        if self.meta.get('include', True):
            # in_reg = False, always.  Points do not include anything.
            return in_reg
        else:
            return np.logical_not(in_reg)
```

Knowing it is a bit of workaround, perhaps I could 'trick' that call setting that meta = {'include' = False} ?

**Comment by mireianievas** [comment] 2022-09-30 12:32
Amazing, the trick seems to work @adonath . All I had to do was setting my

on_pointskyregion.meta = {'include': False}

and then the PointSkyRegion returns the opposite boolean ... True. 

dataset.npred() for the 1D dataset also changed:
 
```
array([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3745e+03, 1.4935e+03,
       6.4250e+02, 3.4000e+02, 1.0000e+02, 5.7500e+01, 3.4000e+01,
       1.8000e+01, 1.2500e+01, 4.5000e+00, 4.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])
```

to 

```
array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.44549339e+03, 1.55626963e+03, 7.01364692e+02, 3.77371018e+02,
       1.29246339e+02, 7.18087605e+01, 4.28105210e+01, 2.38393481e+01,
       1.53224761e+01, 6.62009372e+00, 4.39779027e+00, 1.04601812e+00,
       1.48030733e+00, 1.95032540e-01, 5.64593577e-02, 6.86080656e-03])
```

**Comment by mireianievas** [comment] 2022-09-30 12:34
![image](https://user-images.githubusercontent.com/2607760/193270731-9dc72af5-e48e-4a75-9ad6-c38029cec7b1.png)

**Comment by mireianievas** [comment] 2022-09-30 12:51
I got my hopes too high. The global fit now works, but the FluxPointEstimator still doesn't

```
flux_points = fpe.run(datasets=datasets)

-----------

File ~/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy/estimators/points/sed.py:117, in FluxPointsEstimator.run(self, datasets)
    115 table = table_from_row_data(rows=rows, meta=meta)
    116 model = datasets.models[self.source]
--> 117 return FluxPoints.from_table(
    118     table=table,
    119     reference_model=model.copy(),
    120     gti=datasets.gti,
    121     format="gadf-sed",
    122 )

File ~/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy/estimators/points/core.py:249, in FluxPoints.from_table(cls, table, sed_type, format, reference_model, gti)
    247 for name in cls.all_quantities(sed_type=sed_type):
    248     if name in table.colnames:
--> 249         maps[name] = RegionNDMap.from_table(
    250             table=table, colname=name, format=format
    251         )
    253 meta = cls._get_meta_gadf(table)
    254 return cls.from_maps(
    255     maps=maps,
    256     reference_model=reference_model,
   (...)
    259     gti=gti,
    260 )

File ~/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy/maps/region/ndmap.py:531, in RegionNDMap.from_table(cls, table, format, colname)
    528 if colname is None:
    529     raise ValueError("Column name required")
--> 531 axes = MapAxes.from_table(table=table, format=format)
    533 if colname == "stat_scan":
    534     names = ["norm", "energy"]

File ~/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy/maps/axes.py:1991, in MapAxes.from_table(cls, table, format)
   1989 for axis_format in ["gadf-sed-norm", "gadf-sed-energy", "gadf-sed-counts"]:
   1990     try:
-> 1991         axis = MapAxis.from_table(table=table, format=axis_format)
   1992     except KeyError:
   1993         continue

File ~/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy/maps/axes.py:1320, in MapAxis.from_table(cls, table, format, idx, column_prefix)
   1318 if "datasets" in table.colnames:
   1319     labels = np.unique(table["datasets"])
-> 1320     axis = LabelMapAxis(labels=labels, name="dataset")
   1321 else:
   1322     shape = table["counts"].shape

File ~/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy/maps/axes.py:2763, in LabelMapAxis.__init__(self, labels, name)
   2762 def __init__(self, labels, name=""):
-> 2763     unique_labels = set(labels)
   2765     if not len(unique_labels) == len(labels):
   2766         raise ValueError("Node labels must be unique")

TypeError: unhashable type: 'list'
```

**Comment by adonath** [comment] 2022-09-30 13:11
@mireianievas It seems you use a list a dataset name somewhere in your code, can you check?

**Comment by adonath** [comment] 2022-09-30 13:13
Yes, setting the meta on the regions works, but only accidentally. I'll check whether we still need a small fix in Gammapy...

**Comment by adonath** [comment] 2022-09-30 14:11
@mireianievas Can you please take a brief look at #4118?

**Comment by mireianievas** [comment] 2022-09-30 14:39
I don't think so

```
Datasets
--------

Dataset 0: 

  Type       : MapDataset
  Name       : Fermi-LAT_FRONT
  Instrument : 
  Models     : [ 'diffuse-iem', 'fermi-diffuse-iso-FRONT', 'MySource']

Dataset 1: 

  Type       : SpectrumDatasetOnOff
  Name       : MAGIC
  Instrument : 
  Models     : ['MySource']

```

This is what I pass to the ```FluxPointsEstimator(...).run()```

**Comment by adonath** [comment] 2022-09-30 14:41
Thanks @mireianievas, this looks all good! I'll check once more...

**Comment by adonath** [comment] 2022-09-30 14:47
@mireianievas Which version of Astropy do you use? What is the output of `gammapy info`?

**Comment by mireianievas** [comment] 2022-09-30 15:55
```
Gammapy package:

	version                : 0.20.1     
	path                   : /home/mnievas/anaconda/envs/gammapy-dev/lib/python3.8/site-packages/gammapy 


Other packages:

	numpy                  : 1.23.1     
	scipy                  : 1.8.1      
	astropy                : 5.1        
	regions                : 0.6        
	click                  : 8.1.3      
	yaml                   : 6.0        
	IPython                : 8.4.0      
	jupyterlab             : 3.4.4      
	matplotlib             : 3.5.2      
	pandas                 : 1.4.3      
	healpy                 : 1.16.1     
	iminuit                : 2.15.0     
	sherpa                 : 4.14.1     
	naima                  : 0.10.0     
	emcee                  : 3.1.2      
	corner                 : 2.2.1 
```
I think it is because the Datasets names in one of the models (the one for my source of interest) is indeed a list. 

```
Component XX: SkyModel

  Name                      : XXX
  Datasets names            : ['Fermi-LAT_FRONT', 'MAGIC']
  Spectral model type       : CompoundSpectralModel
  Spatial  model type       : PointSpatialModel
  Temporal model type       : 
  Parameters:
    amplitude                     :   1.70e-08   +/- 3.4e-09 1 / (cm2 s TeV)
    reference             (frozen):     10.000       GeV         
    alpha                         :      1.955   +/-    0.04             
    beta                          :      0.020   +/-    0.01             
    alpha_norm            (frozen):      1.000                   
    redshift              (frozen):      0.100                   
    lon_0                 (frozen):    XXX      deg         
    lat_0                 (frozen):     XXX       deg   
```

**Comment by mireianievas** [comment] 2022-09-30 16:00
I found this

```
class LabelMapAxis:
    """Map axis using labels

    Parameters
    ----------
    labels : list of str
        Labels to be used for the axis nodes.
    name : str
        Name of the axis.

    """

    node_type = "label"

    def __init__(self, labels, name=""):
        unique_labels = set(labels)
        if not len(unique_labels) == len(labels):
            raise ValueError("Node labels must be unique")

        self._labels = np.array(labels)
        self._name = name
```

why do we convert from a list of str into a set? just to get the unique ones? why not doing a np.unique(labels) and then we do not need to do the conversion into np.array() ?

**Comment by adonath** [comment] 2022-09-30 16:16
@mireianievas I have looked into the issue and it is related to the fact that the datasets cover a different energy range. So there are flux points where only one of each dataset contributes, and there are points where both contribute.

This is currently not handled by Gammapy...I'll check if there is a workaround.

**Comment by mireianievas** [comment] 2022-09-30 17:36
![image](https://user-images.githubusercontent.com/2607760/193324774-4a3b2d35-268e-4977-97f4-315f0dc1fd09.png)

I had to make a few changes in some places though:

Adding in gammapy/maps/maps.py

```
def __setitem__(self, key, value):
        if value is not None and not isinstance(value, Map) and **not isinstance(value,RegionNDMap):**
```

In gammapy/maps/axes.py replace set(labels) by np.unique(labels). Then self._labels = unique_labels (no need to make a copy as a np.array anymore.

```
   def __init__(self, labels, name=""):
        print(labels)
        #unique_labels = set(labels)
        unique_labels = np.unique(labels)

        if not len(unique_labels) == len(labels):
            raise ValueError("Node labels must be unique")

        self._labels = unique_labels #np.array(labels)
        self._name = name
```

**Comment by adonath** [comment] 2022-09-30 18:01
@mireianievas I'm proposing a different fix in #4118. But I also like the simplification introduced by using `np.unique`, feel free to open a PR and contribute this. 

I'm less convinced about the change in `__setitem__`. `RegonNDMap` inherits from `Map` so the statement should have no effect...

**Comment by mireianievas** [comment] 2022-09-30 18:14
@adonath does #4118 already include some fixes for the data points? 

I introduced the RegionNDMap change because, despite inherting Map, it enters that if statement for some reason.

**Comment by mireianievas** [comment] 2022-09-30 22:27
By the way, shouldn't this be an element-wise comparison?

```
changed = self._cached_parameter_values_previous == values
```

in gammapy/datasets/evaluator.py:404

```
    def parameter_norm_only_changed(self):
        """Only norm parameter changed"""
        norm_only_changed = False
        idx = self._norm_idx
        values = self.model.parameters.value
        if idx and self._computation_cache is not None:
            changed = self._cached_parameter_values_previous == values
            norm_only_changed = sum(changed) == 1 and changed[idx]
        if not norm_only_changed:
            self._cached_parameter_values_previous = values
        return norm_only_changed
```

**Comment by adonath** [comment] 2022-10-04 00:33
> By the way, shouldn't this be an element-wise comparison?

It is a Numpy array which is compared element-wise. I don't see any issue here.

In #4118 I added the fix for the first issue. The support for datasets of multiple instruments requires and adaption of the current methods to be well defined. I opened a reminder issue to support this in #4123.

**Comment by mireianievas** [comment] 2022-10-11 10:02
Sorry to rebump this. 

It should be fixed in the main repository, right?

I synced it yesterday and it does not look like it is fixed yet

![image](https://user-images.githubusercontent.com/2607760/195060221-a23402ff-ec82-49d0-bb2c-adef7ac2c53a.png)

```
>> git rev-parse --abbrev-ref HEAD
main
```

I synced it yesterday (last commit I have is from Oct 7).

**Comment by adonath** [comment] 2022-10-11 12:54
@mireianievas Yes, the specific fix for this issue is included. However it still requires that the center of the point region and the position of the model basically **exactly** agree. Is this the case?

**Comment by adonath** [comment] 2022-10-11 12:56
@registerrier I think we should maybe still add a note in our docs that in the joint fit scenario with a `PointSourceRegion` and varying rad max the position of the source cannot be fitted and should always be frozen.

**Comment by mireianievas** [comment] 2022-10-11 16:25
then maybe there should be a message, or log or something saying which datasets are used and which aren't. Right now it is completely silent I think, it is not straightforward to check if the data is being used at all. 

But I personally think this is not how it should be. In a Point-like / 1D analysis, at least at this late stage of the analysis, position accuracy is not that relevant. One knows which source is being observed and in this particular case, even if LST is managing internally a source region a few arcsecs off from that of LAT, that should make no difference and the summed likelihood should be allowed.

**Comment by mireianievas** [comment] 2022-10-11 18:15
Same fit with the old method (they should agree) of defining a model with only a spectral component for the LST data

![image](https://user-images.githubusercontent.com/2607760/195168279-eaa86aae-ab3e-462c-abbc-862d3fee54af.png)


The confidence band is super thin (even if the spectrum has quite high significance because it is a bright source, maybe the constraints are a bit too good). 

I made sure I used the same coordinates to define the ON region in my LST dataset analysis. And it returns True when I call manually the contains() function from my Jupyter notebook using that ON region. So I don't know what can be wrong, but for now it does not seem like the fix works in this particular case.

**Comment by adonath** [comment] 2022-10-11 18:34
Thanks @mireianievas for checking again! I'll investigate once more...

**Comment by adonath** [comment] 2022-10-11 19:59
Just confirm @mireianievas , the issue was not correctly addressed by #4118. I have opened a new PR in #4133. DO you have time to check and confirm the fix? Thanks!

**Comment by mireianievas** [comment] 2022-10-11 20:21
let me check it @adonath , thanks for the pull request !.

**Comment by adonath** [comment] 2022-10-11 20:44
@mireianievas Consistent with the behavior for e.g. `MapDataset` with a `WcsGeom` Gammapy allows for a shift in position by `0.1 deg`, defined by https://github.com/gammapy/gammapy/blob/main/gammapy/datasets/evaluator.py#L13.

**Comment by mireianievas** [comment] 2022-10-11 20:56
No, it does not seem to give the expected results

![image](https://user-images.githubusercontent.com/2607760/195196676-ea86f1bd-b2e3-400e-a7cb-2559f087c6a8.png)

**Comment by adonath** [comment] 2022-10-11 20:59
@mireianievas have you checked out the branch with the fix? It is not merged yet...

**Comment by mireianievas** [comment] 2022-10-11 21:00
@adonath yes, I checked out the pull request directly

```
git fetch -u origin pull/4133/head:main
pip install .
```

**Comment by mireianievas** [comment] 2022-10-11 21:10
Just to make sure

```
![image](https://user-images.githubusercontent.com/2607760/195198959-7bd447eb-f07b-4647-9a49-bd1b8051a6bf.png)
```

So yes, the notebook is using the correct PR.

**Closed** 2022-10-14 10:00 UTC
Labels: bug
