### ISSUE TITLE
ImportError: libgfortran.so.4 with conda Sherpa 4.10

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1417] opened 2018-05-11 18:06 UTC
In Gammapy we have a build that now fetches Sherpa 4.10 and fails like this:
https://travis-ci.org/gammapy/gammapy/jobs/377744827#L3797
```
$ python -c 'import sherpa.optmethods'
...
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/optmethods/optfcts.py:29: ImportError
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
...
```

I think basically we do the equivalent of this in our `.travis.yml`, but I'm not sure:
```
conda channel --add conda-forge sherpa
conda install sherpa libgfortran
```

This build used to work with Sherpa 4.9, so presumably something changed in 4.10?
Or is our `.travis.yml` no good and we fetch e.g. a wrong `libgfortran` for some reason?
@olaurino - Help?

PS: locally on Mac with Sherpa 4.10 from conda all Gammapy tests pass.

**Comment by cdeil** [comment] 2018-07-29 16:30
I have Sherpa 4.10 locally on Mac from conda, and here is a build using Sherpa 4.10 with Linux:
https://travis-ci.org/gammapy/gammapy/jobs/409535201#L2301
Everything looks OK.

We also didn't have any users or devs complain about this issue.

So I'm closing this now. If someone finds the issue in the future, please re-open or file a new one.

**Comment by olaurino** [comment] 2018-07-30 14:33
@cdeil sorry I don't remember seeing this issue despite the specific mention, at least until this morning when I got a notification that you closed it. I apologize for not getting back to you. Please let me know if we can still be of assistance.

**Comment by cdeil** [comment] 2018-07-30 14:35
Omar - thanks!

In the future I'll try to track down issues better and open a ticket in your Sherpa tracker.

**Comment by cdeil** [comment] 2018-08-21 21:51
This error started to appear again on Sherpa import
```
 ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```
in this build yesterday:
https://travis-ci.org/gammapy/gammapy/jobs/418891147#L3539

@olaurino - Any idea why?

You didn't make a release, right? So it must have something to do with other conda or conda-forge packages or setup that changed somehow?

**Comment by olaurino** [comment] 2018-08-22 14:44
> So it must have something to do with other conda or conda-forge packages or setup that changed somehow?

It looks like it. Ugh. I'll take a look.

**Comment by olaurino** [comment] 2018-08-22 15:55
I can't reproduce exactly the sequence of packages being installed, which might or might not impact my ability to reproduce the issue.

In particular, it looks like for some reason you are forcing downgrading `conda` to a specific version (4.3) from conda-forge. However, after I do that, if I try to create a new channel with python 2.7 I get an installation plan with all packages from the conda-forge channel. If I edit the `~/.condarc` to give the standard channel priority over conda-forge then I only get packages from the default channel. Playing with the priorities (e.g. giving the sherpa channel a higher priority) doesn't seem to make a difference.

The main issue is that in your travis logs the `libgcc-ng` and similar packages are installed from the 8.2 series and what looks like the default channel, while in my attempts to reproduce the issue they are from the 7.2 series. I'll keep trying to reproduce the issue, maybe I'll succeed anyway.

I looked into the astropy's `ci-helpers` scripts and it looks like there is a lot of complexity in there. That's where the conda version is pinned down, and even some package pinning might be happening.

@cdeil would it be possible to run one of these jobs with the `$DEBUG` variable set to "True"? That might spit out some useful information. I'll keep trying to reproduce the issue in the meantime.

**Comment by cdeil** [comment] 2018-08-22 15:59
@olaurino - thank you for your effort and time!

> @cdeil would it be possible to run one of these jobs with the $DEBUG variable set to "True"? That might spit out some useful information. I'll keep trying to reproduce the issue in the meantime.

Of course if it helps we should do that.

Just make a PR with this change to trigger a build, or let me know where exactly I should make an edit in `.travis.yml`.

**Comment by cdeil** [comment] 2018-08-30 11:16
@olaurino - I have no idea which of the Fortran linking / packaging options you are considering is better. https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html is probably relevant, but I'm sure you're aware of that. Probably another good thing to do is to look at what scipy does to build and distribute via conda, since they are very widely used and also have Fortran.

**Comment by cdeil** [comment] 2018-10-17 20:08
This install issue was resolved via the latest Sherpa release:
https://github.com/sherpa/sherpa/releases/tag/4.10.1

They removed the Fortran dependency in  https://github.com/sherpa/sherpa/pull/481 (we don't use xspec in Gammapy).

This build from a few days ago is with Sherpa 4.10.0 and has the libgfortran link error:
https://travis-ci.org/gammapy/gammapy/jobs/440784483#L2483

This build is from today with Sherpa 4.10.1 and passed without error:
https://travis-ci.org/gammapy/gammapy/jobs/442767281#L2477

@olaurino - Thanks!  🚀🥇 🍕 🍻

**Closed** 2018-10-17 20:08 UTC
Labels: bug, infrastructure

**Comment by bsipocz** [comment] 2018-10-17 20:16
@cdeil - I'm sorry, this ping has lost in the weeds of my move. Next time try to ping me elsewhere, too if there is no initial response.
