### ISSUE TITLE
Failing spectrum analysis test 

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#408] opened 2016-01-02 19:26 UTC
This tests is failing in #392. Based on the history and ``git blame`` I guess @joleroi and @cdeil may have an idea how to fix it. It only fails with py2.7.

Travis log: https://travis-ci.org/gammapy/gammapy/jobs/99854091#L1446
https://travis-ci.org/gammapy/gammapy/builds/99854081

``gammapy/spectrum/tests/test_spectrum_analysis.py``

**Comment by bsipocz** [comment] 2016-01-02 23:18
There also got another fail locally from the same file:

```
__________________________________________________ test_spectral_fit ___________________________________________________

tmpdir = local('/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pytest-bsipocz/pytest-7/test_spectral_fit0')

    @pytest.mark.skipif('NUMPY_LT_1_9')
    @requires_dependency('sherpa')
    @requires_data('gammapy-extra')
    def test_spectral_fit(tmpdir):
        pha1 = gammapy_extra.filename("datasets/hess-crab4_pha/pha_run23592.pha")
        pha2 = gammapy_extra.filename("datasets/hess-crab4_pha/pha_run23526.pha")
        pha_list = [pha1, pha2]
        fit = SpectralFit(pha_list)
        fit.model = 'PL'
        fit.energy_threshold_low = '100 GeV'
        fit.energy_threshold_high = '10 TeV'
        fit.run(method='sherpa')
>       assert_allclose(fit.model.gamma.val, 2.0, rtol=1e-1)

gammapy/spectrum/tests/test_spectrum_analysis.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/sw/lib/python2.7/site-packages/numpy/testing/utils.py:1347: in assert_allclose
    verbose=verbose, header=header)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

comparison = <function compare at 0x10ebf4d70>, x = array(2.230029367207114), y = array(2.0), err_msg = ''
verbose = True, header = 'Not equal to tolerance rtol=0.1, atol=0', precision = 6

    def assert_array_compare(comparison, x, y, err_msg='', verbose=True,
                             header='', precision=6):
        from numpy.core import array, isnan, isinf, any, all, inf
        x = array(x, copy=False, subok=True)
        y = array(y, copy=False, subok=True)
    
        def safe_comparison(*args, **kwargs):
            # There are a number of cases where comparing two arrays hits special
            # cases in array_richcompare, specifically around strings and void
            # dtypes. Basically, we just can't do comparisons involving these
            # types, unless both arrays have exactly the *same* type. So
            # e.g. you can apply == to two string arrays, or two arrays with
            # identical structured dtypes. But if you compare a non-string array
            # to a string array, or two arrays with non-identical structured
            # dtypes, or anything like that, then internally stuff blows up.
            # Currently, when things blow up, we just return a scalar False or
            # True. But we also emit a DeprecationWarning, b/c eventually we
            # should raise an error here. (Ideally we might even make this work
            # properly, but since that will require rewriting a bunch of how
            # ufuncs work then we are not counting on that.)
            #
            # The point of this little function is to let the DeprecationWarning
            # pass (or maybe eventually catch the errors and return False, I
            # dunno, that's a little trickier and we can figure that out when the
            # time comes).
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", category=DeprecationWarning)
                return comparison(*args, **kwargs)
    
        def isnumber(x):
            return x.dtype.char in '?bhilqpBHILQPefdgFDG'
    
        def chk_same_position(x_id, y_id, hasval='nan'):
            """Handling nan/inf: check that x and y have the nan/inf at the same
            locations."""
            try:
                assert_array_equal(x_id, y_id)
            except AssertionError:
                msg = build_err_msg([x, y],
                                    err_msg + '\nx and y %s location mismatch:'
                                    % (hasval), verbose=verbose, header=header,
                                    names=('x', 'y'), precision=precision)
                raise AssertionError(msg)
    
        try:
            cond = (x.shape == () or y.shape == ()) or x.shape == y.shape
            if not cond:
                msg = build_err_msg([x, y],
                                    err_msg
                                    + '\n(shapes %s, %s mismatch)' % (x.shape,
                                                                      y.shape),
                                    verbose=verbose, header=header,
                                    names=('x', 'y'), precision=precision)
                if not cond:
                    raise AssertionError(msg)
    
            if isnumber(x) and isnumber(y):
                x_isnan, y_isnan = isnan(x), isnan(y)
                x_isinf, y_isinf = isinf(x), isinf(y)
    
                # Validate that the special values are in the same place
                if any(x_isnan) or any(y_isnan):
                    chk_same_position(x_isnan, y_isnan, hasval='nan')
                if any(x_isinf) or any(y_isinf):
                    # Check +inf and -inf separately, since they are different
                    chk_same_position(x == +inf, y == +inf, hasval='+inf')
                    chk_same_position(x == -inf, y == -inf, hasval='-inf')
    
                # Combine all the special values
                x_id, y_id = x_isnan, y_isnan
                x_id |= x_isinf
                y_id |= y_isinf
    
                # Only do the comparison if actual values are left
                if all(x_id):
                    return
    
                if any(x_id):
                    val = safe_comparison(x[~x_id], y[~y_id])
                else:
                    val = safe_comparison(x, y)
            else:
                val = safe_comparison(x, y)
    
            if isinstance(val, bool):
                cond = val
                reduced = [0]
            else:
                reduced = val.ravel()
                cond = reduced.all()
                reduced = reduced.tolist()
            if not cond:
                match = 100-100.0*reduced.count(1)/len(reduced)
                msg = build_err_msg([x, y],
                                    err_msg
                                    + '\n(mismatch %s%%)' % (match,),
                                    verbose=verbose, header=header,
                                    names=('x', 'y'), precision=precision)
                if not cond:
>                   raise AssertionError(msg)
E                   AssertionError: 
E                   Not equal to tolerance rtol=0.1, atol=0
E                   
E                   (mismatch 100.0%)
E                    x: array(2.230029367207114)
E                    y: array(2.0)

/sw/lib/python2.7/site-packages/numpy/testing/utils.py:708: AssertionError
------------------------------------------------- Captured stdout call -------------------------------------------------
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.plot.pylab_backend; plotting routines will not be available
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
read ARF file /Users/bsipocz/munka/devel/gammapy-extra/datasets/hess-crab4_pha/arf_run23592.fits
read RMF file /Users/bsipocz/munka/devel/gammapy-extra/datasets/hess-crab4_pha/rmf_run23592.fits
read background file /Users/bsipocz/munka/devel/gammapy-extra/datasets/hess-crab4_pha/bkg_run23592.fits
read ARF file /Users/bsipocz/munka/devel/gammapy-extra/datasets/hess-crab4_pha/arf_run23526.fits
read RMF file /Users/bsipocz/munka/devel/gammapy-extra/datasets/hess-crab4_pha/rmf_run23526.fits
read background file /Users/bsipocz/munka/devel/gammapy-extra/datasets/hess-crab4_pha/bkg_run23526.fits
Datasets              = 1, 2
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 63.925
Final fit statistic   = 25.2066 at function evaluation 204
Data points           = 60
Degrees of freedom    = 58
Probability [Q-value] = 0.999947
Reduced statistic     = 0.434597
Change in statistic   = 38.7184
   powlaw1d.default.gamma   2.23003     
   powlaw1d.default.ampl   2.28606e-20 
WARNING: parameter value powlaw1d.default.ampl is at its minimum boundary 0.0
--------------------------------------------------- pytest-selenium ----------------------------------------------------

```

**Comment by joleroi** [comment] 2016-01-07 10:17
I have tried to solve this issue many times. The problem is that Sherpa tries to fit a 2D gaussian model to a spectral dataset. The gaussian model must be set by some other test in gammapy and the Sherpa session somehow remebers this. I tried to fix this with @adonath but we did not succeed.

**Comment by bsipocz** [comment] 2016-01-07 19:14
@joleroi - Sure, no didn't mean any rush with this issue.

However I think for tests like these (that should work in theory but are difficult to make them do so) it's better to xfail them than to allow a fail in master.

**Comment by joleroi** [comment] 2016-01-08 13:25
#403 fixes this, can I close?

**Comment by bsipocz** [comment] 2016-01-08 13:30
@joleroi - Not sure what's gammapy's policy but in other packages we only close issues after the fixes are merged. Alternatively you can write "closes #408" in either a commit message or in the main comment part of the PR, so github will do it automatically.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by cdeil** [comment] 2016-01-08 13:56
@joleroi - I find it annoying at times as well, but it's really better to keep issues open until the corresponding PR is merged. Usually the reporter (or maintainers like me) will look over the issue again and check if the issue really is fully adressed, i.e. fixed / covered by tests.

**Comment by joleroi** [comment] 2016-01-11 07:18
@cdeil, sounds reasonable !
@bsipocz, thanks, for the link. I didn't know that :+1:

**Closed** 2016-01-15 08:04 UTC
