### ISSUE TITLE
Hard coded input for e_true in Analysis for 1D

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2669] opened 2019-12-05 16:23 UTC
**Gammapy version**
v0.15

**Bug description**
If one wants to use 1D spectral analysis with the HLI, `e_true` cannot be set by the `AnalysisConfig`. It is hard coded to be `e_true=np.logspace(-2, 2.5, 109) * u.TeV`.

**Expected behavior**
I would assume to have :
`e_true = self._make_energy_axis(datasets_settings.geom.axes.energy_true).edges`
and either `e_true = e_reco` if none is defined in the `AnalysisConfig`.
Or possibly ``e_true=np.logspace(-2, 2.5, 109) * u.TeV`

**Comment by adonath** [comment] 2019-12-05 16:35
Strangely enough this is also an issue for the 3d analysis in the other direction see https://github.com/gammapy/gammapy/issues/2668#issuecomment-562206103 :-)

**Comment by registerrier** [comment] 2019-12-06 15:03
A solution here could be to remove the default values for the `EnergyAxisConfig` defined in `~gammapy.analysis.AnalysisConfig`. 
It might be safer not to have any default values for the energy axis.

**Comment by Bultako** [comment] 2020-01-28 17:08
@registerrier 
Sorry to arrive so late here.
I guess you solved it in https://github.com/gammapy/gammapy/commit/f8b4fd053c4471e9a944101fa3e1468bc5b25c38

Closing?

**Comment by adonath** [comment] 2020-01-30 18:54
Taking a look at the current implementation it seems, the issue is not solved. We still have default value coded here: https://github.com/gammapy/gammapy/blob/master/gammapy/analysis/config.py#L98 Is this correct?

**Comment by registerrier** [comment] 2020-01-30 20:53
Yes the specific issue of the 1D binning is now solved. This specific issue could probably be closed. see https://github.com/gammapy/gammapy/commit/f8b4fd053c4471e9a944101fa3e1468bc5b25c38

Yet the issue of the default value of the true energy axis stil remains. And I guess issue #2668 is more connected to this than to the `EDispMap`.

**Comment by adonath** [comment] 2020-09-16 08:05
I think at some point we discussed introducing instrument specific default values in Gammapy for the IRFs. I still think this is a good idea. For now I would propose to keep it really simple and add a single `DEFAULT_GEOMS` somewhere in `gammapy.datasets` or possibly `gammapy.maps`.

I think it should look something like this:
```python3

DEFAULT_AXES = {
    "hess": {
        "energy_axis_true": MapAxis.from_energy_bounds(),
        "theta_axis": MapAxis.from_bounds(),
        "migra_axis": MapAxis.from_bounds(),
        "binsz_irf": "0.2 deg"
    },
    "cta": {
        "energy_axis_true": MapAxis.from_energy_bounds(),
        "theta_axis": MapAxis.from_bounds(),
        "migra_axis": MapAxis.from_bounds(),
        "binsz_irf": "0.2 deg"
    },
    "hawc": {
        "energy_axis_true": MapAxis.from_energy_bounds(),
        "theta_axis": MapAxis.from_bounds(),
        "migra_axis": MapAxis.from_bounds(),
        "binsz_irf": "1 deg"
    },
}

```

The structure is such that the dicts can be just passed on to `MapDataset.create()` in addition to the reference `geom` object.

**Comment by adonath** [comment] 2020-09-16 09:23
I'll close this issue, the remaining discussion can be done in #2482.

**Closed by adonath** 2020-09-16 09:23 UTC
Labels: bug, priority-high
