### ISSUE TITLE
Change the first dataset name in `.info_table()`

### ISSUE THREAD

**Issue by aaguasca** [gammapy/gammapy#3801] opened 2022-02-14 08:10 UTC
**Is your feature request related to a problem? Please describe.**
When the method `.info_table()` is used in a Datasets object, the name of the first dataset in the output table is always "stacked". This rename is done even if the parameter `cumulative` of `.info_table()` is set to False.

**Describe the solution you'd like**
Keep the original name of the first dataset in the returned table if `cumulative`=False and only use "stacked" when `cumulative`=True.

**Comment by adonath** [comment] 2022-02-14 13:25
Thanks @aaguasca ! I think the issue is addressed in https://github.com/gammapy/gammapy/pull/3498. But maybe we can implement the fix independently before...

**Comment by aaguasca** [comment] 2022-02-14 21:56
I did not know it, sorry. If you want to do so, I am happy to help.

**Closed** 2022-05-05 19:13 UTC
Labels: feature
