### ISSUE TITLE
Optional keywords required by gammapy

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3352] opened 2021-05-07 11:35 UTC
Following up on #3119, I created 

1.  a minimal `obs_index_table` and `hdu_index_table` using only the mandatory keywords listed in https://gamma-astro-data-formats.readthedocs.io/en/v0.2/data_storage/index.html. 

-  'DEADC' is read from  the obs table in `MapDataset.make_exposure()`

2. Creating a minimum events file, `ev` with only required meta,

- `ev.observation_time_duration` , `ev.altaz, `fails with `KeyError: 'MJDREFI'` (and start/stop time)
- `ev.altaz_from_table` fails with `KeyError: 'AZ'
- `ev.offset` fails with `KeyError: 'RA_PNT'
- Q: Writing events files?

This is a testing in progress. Will keep updating  

Question: How to do a systematic test?

**Comment by adonath** [comment] 2021-11-12 15:08
I will close this issue as basically a duplicate of #3119. We can continue discussion there.

**Closed by adonath** 2021-11-12 15:08 UTC
Labels: bug
