### ISSUE TITLE
Add additional info in meta table

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3795] opened 2022-02-11 10:18 UTC
Hi! I propose to add the observation zenith angle in `Dataset.meta_table`
https://github.com/gammapy/gammapy/blob/2ad1aaa9436d8dd8add3d27ae6522c829a010106/gammapy/makers/map.py#L276

**Comment by adonath** [comment] 2022-03-22 19:22
Closing as duplicate of #2452.

**Closed by adonath** 2022-03-22 19:22 UTC
