### ISSUE TITLE
CTAObservationSimulation is broken

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#962] opened 2017-04-06 11:49 UTC
I don't know exactly when this happened, but I don't think there is a unit test in gammapy so nobody noticed. This is also the reason why the notebook tests fail at the moment, I think

https://travis-ci.org/gammapy/gammapy/jobs/218368596

@jjlk It's hard for me to fix the class since I don't quickly see what it's supposed to do. Can you add a test?

**Comment by jjlk** [comment] 2017-04-06 12:15
Hi @joleroi , yes it's broken because the way to compute the expected excess changed. It's easy to fix by removing the `e_reco=e_reco_axis`. Should I do a pull request for that?

But the problem is that the fix is not enough to get good results.

**Comment by jjlk** [comment] 2017-04-06 12:16
And tests exist but results of the simulation are not tested

**Comment by jjlk** [comment] 2017-04-06 12:35
Hi @joleroi , fix is in PR #963.

I'll open an issue for the non-results we get.

**Comment by joleroi** [comment] 2017-04-06 12:40
> And tests exist but results of the simulation are not tested

It's weird that they did not fail, the should have because of the change to the predicted counts computation

**Comment by joleroi** [comment] 2017-04-07 14:43
I xfailed the notebook test in https://github.com/gammapy/gammapy-extra/commit/d83fb7f215dd5aaad86880eff39dbfc1af9b2388  to get a clean gammapy master again

**Comment by cdeil** [comment] 2017-04-11 06:43
I'm not 100%, but I think this is resolved?
Closing this issue now.

@jjlk - For the future: we need to have "normal" tests that execute analysis code and assert on some result. If we don't have that, it's very hard to refactor and improve code in Gammapy and thing are likely to break as we work on Gammapy. All we test for the notebooks is that they don't raise an exception, to help us notice when they need updating after changes in Gammapy.

**Closed by cdeil** 2017-04-11 06:43 UTC
Labels: bug

**Comment by cdeil** [comment] 2017-04-11 06:45
For reference:

Notebook update commit: https://github.com/gammapy/gammapy-extra/commit/a97d12863bbd6da82d1baae14acde13f50fffdf6
Current version: https://github.com/gammapy/gammapy-extra/blob/a97d12863bbd6da82d1baae14acde13f50fffdf6/notebooks/cta_simulation.ipynb
