### ISSUE TITLE
Missing memory management of MapDataset

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#3530] opened 2021-09-28 15:02 UTC
**Gammapy version**
v0.18.2

**Bug description**
I fit the background model for a list of observations, stacking the fitted datasets as I go, like this:
```python
stacked_dataset = MapDataset.create(geom=geom)
for obs in observations:
    dataset = MapDataset.read('dataset-obs-{}.fits.gz'.format(obs.obs_id))

    # create background model with tilt parameter free
    spectral_model = PowerLawNormSpectralModel()
    spectral_model.parameters['tilt'].frozen = False
    bkg_model = FoVBackgroundModel(dataset_name=dataset.name, spectral_model=spectral_model)
    dataset.models = bkg_model

    # adjust background
    with np.errstate(divide='ignore', invalid='ignore', over='ignore'):
        dataset = maker_fov.run(dataset)

    # stack
    stacked_dataset.stack(dataset)

    del bkg_model
    del dataset
```
I'm doing this in a Jupyter notebook, and the memory consumption of this notebook keeps steadily increasing, until at some point I get a memory error.

**Expected behavior**
The memory consumption should not increase continuously.

**Other information**
I do realize that I could (or should?) copy the code into a script, run it on a subset of the observations, write the stacked dataset to disk, then re-run the script and read the stacked dataset from disk again. This is a bit tedious though, and in principle I wouldn't expect that there is a memory leak here. But possibly I'm doing something wrong - would be grateful for any hints in this case :-)

**Comment by lmohrmann** [comment] 2021-09-30 08:43
Checking a bit further, it seems that neither `del bkg_model` nor `del dataset` has any effect on the memory usage. So the issue is probably not with the `FoVBackgroundMaker` but with missing memory handling of the `MapDataset` class, for instance...?

**Comment by registerrier** [comment] 2021-09-30 08:45
Yes possibly. How many files do you typically open and stack? How large are the datasets?

**Comment by lmohrmann** [comment] 2021-09-30 08:56
> I do realize that I could (or should?) copy the code into a script, run it on a subset of the observations, write the stacked dataset to disk, then re-run the script and read the stacked dataset from disk again. 

I just tried this, but it didn't work either - it used to work this way with Gammapy v0.17, so there even seems to be a degradation here?

I have O(100) data sets that I want to fit and then stack. Each data set has ~50 MB on disk, but the script/notebook reaches 10GB of memory before even having read in 100 data sets.

So it seems the only way of achieving this is to run my script multiple times, on separate chunks of data sets...?

And for the future, it would be desirable to add memory handling to the `MapDataset` class (and others, I guess)...?

**Comment by adonath** [comment] 2021-09-30 09:49
@lmohrmann Could you maybe provide a minimal example that reproduces the issue with public data from GAMMAPY_DATA?

And maybe check whether the issue is still present in dev version. As far as I know our benchmarks do not show anything...

**Comment by adonath** [comment] 2021-09-30 09:54
@lmohrmann If handled correctly Python does all the memory management. The example you have shown above cannot really contain such a memory issue, because the local variables created in the for loop are garbage collected, once they go out of scope. The issue must be connected to code that is not shown in the example...

**Comment by adonath** [comment] 2021-11-01 16:26
@lmohrmann Any progress here in reproducing the issue?

**Comment by lmohrmann** [comment] 2021-11-02 19:14
Apologies, no time yet to investigate this in more detail. I really wouldn't know which other parts in my script would be causing a leak, but as I said, I could not properly test this. Next weeks will be quite busy for me as well, so at this point I cannot promise that I will be able to provide more info on a reasonable time scale for you... Feel free to close the issue for now - I can re-open whenever I have more substantial evidence for a problem.

**Comment by registerrier** [comment] 2022-01-21 18:36
Hi @lmohrmann , have you tried to reproduce the issue with v0.19? Is it still failing?

**Comment by lmohrmann** [comment] 2022-01-24 07:59
Hi @registerrier, no, I have not. Might be able to give it a try next week, if you think that is still helpful... No promises though, many things on my plate right now...

**Comment by adonath** [comment] 2022-03-22 19:27
Will close this issue, due to lack of confirmation. Please open @lmohrmann, if the issue remains.

**Closed by adonath** 2022-03-22 19:27 UTC
Labels: bug
