### ISSUE TITLE
Spectral points from Minuit OK?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1635] opened 2018-08-03 12:30 UTC
Yesterday @joleroi changed the default fitter for SpectrumFit and flux point estimation to Minuit.

I think it's basically working, see here:
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/cta_data_analysis.ipynb

@bkhelifi - Can you add a link here to your CTA AGN notebook where the spectral points are not OK any more? Extra points if you give values for one point what it was before and what it is now, so that we know what to debug exactly.

@joleroi or @mealworm - Is there a way to suppress the fit result output per spectral point per default, and instead just give status in the summary table? Or add an option whether users want to see that much output in the Jupyter notebook?

**Comment by bkhelifi** [comment] 2018-08-03 12:45
Hi all,

I have noticed two issues with the latest version of the SpectrumAnalysis. I used this notebook for my  test: [https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/agn_j1224/TeV_J1224p212_DC1_spectrum.ipynb]( https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/agn_j1224/TeV_J1224p212_DC1_spectrum.ipynb).

1. We can not plot anymore the bkg counts. I think it is due to the fact that the background counts are not stored anymore in the spectrum result object: See in spectrum.fit.py, l403 in results.append(SpectrumFitResult(...)), there is no more npred_bkg!

2. There is an issue when computing the TS in FluxPointEstimator. Look at the output table of the notebook: the dnde_err is very large and the sqrt_ts is increasing... Maybe it is linked to the fact that the model parameters errors are not defined in flux_point.py, fit_point function: l765 'fit = SpectrumFit(self.obs, model)'.

**Comment by joleroi** [comment] 2018-08-07 12:39
> I think it is due to the fact that the background counts are not stored anymore in the spectrum result object

You are right ... Is the background prediction ``mu_bkg`` from WSTAT an important debug number, should it somehow be added back?

I will have look at your second point

**Comment by bkhelifi** [comment] 2018-08-10 07:53
Hi,
I ran the AGN notebook... So:
- For my question #1: no crash anymore! But I think it is important to plot mu_bkg is order to have an idea of the S/N ratio. To answer to @joleroi, I will be happy to add back mu_bkg
- For my question #2: there is still an issue with the estimation of TS! Ex:
e_ref | e_min | e_max | dnde | dnde_err | dnde_ul | is_ul | sqrt_ts | dnde_errp | dnde_errn
19.0546071796 | 13.1825673856 | 27.5422870334 | 6.56470112602e-13 | 1.41421356237 | 6.59752463166e-13 | False | 25.4981432656 | 1.00974195868e-28 | 7.67732782251e-13
Having a TS of about 25 when the dnde_err/dnde>>1 is not possible... There should be a remaining issue! As a consequence probably, the UL values might be incorrect, at least they look like...
@joleroi : could you have a look?

The good news now is that the spectral analysis results are fully compatible between the 1D and the 3D!! A really improvement. Do you have an explanation of such change in the 1D results?

**Comment by adonath** [comment] 2018-08-13 11:40
@bkhelifi I'd like to investigate the issue with the TS values of flux points, but unfortunately the notebook (`TeV_J1224p212_DC1_spectrum.ipynb`) is broken. It fails with an `IndexError`, because the reflected region background estimator does not find any off regions. Can you try to fix it and let me know?

**Comment by lmohrmann** [comment] 2018-09-17 19:33
I have an issue with (some) flux points as well after switching to the minuit minimizer. In my particular case, the problems seem to appear in cases where the number of ON counts is zero. I obtain a non-zero best-fit amplitude in one case, indicating that the minimization failed. Indeed, if I calculate the `total_stat` value for the best-fit amplitude and amplitude equal to zero, I obtain a much smaller (i.e. better) value for the latter case (as I would expect).

The first problem is that this currently goes undetected. I think there should be a check in `compute_flux_point_sqrt_ts` that ensures that `stat_null-stat_best_fit` and `amplitude` have the same sign. That should catch cases where the minimization clearly failed.

The other question is why the minimization fails at all. I don't have a good idea yet, but as I said, for me it appears in cases for which there are no ON counts. Any ideas?

**Comment by cdeil** [comment] 2018-09-17 19:57
The best way to make progress and debug anything related to flux point is to compute and store likelihood profiles like this:

https://gamma-astro-data-formats.readthedocs.io/en/latest/spectra/binned_likelihoods/index.html#likelihood-sed

Especially with 1 parameter fits it's then usually possible to figure out what the optimiser or root finder is doing.

Maybe the likelihood isn't well-behaved in the n_on = 0 case?
Is this with wstat?
I think in that simple case you can even check the likelihood profile used in the fit against the formulat here: http://docs.gammapy.org/dev/stats/fit_statistics.html#special-cases

Good additions to Gammapy would be
- test case that reproduces the non-converging fit
- return fit status for each point in the results dict / table
- add some code to compute a likelihood profile.

I know we're all short on time, but @lmohrmann or @adonath - if you could try to debug and work on this, that would be great. Putting this on v0.8 for now, since it's pretty important and several people seem to run into this "issue" (which in the end could just be that we should more clearly return "you have no counts here, just use the UL value or forget about this point completely".

**Comment by adonath** [comment] 2018-09-18 08:44
@lmohrmann The issue that you describe sounds like a weird case, where the likelihood is actually not improved but worsened by the optimizer, which is exactly what you say: a failed fit. But note that this is independent of the sign of the `amplitude`. In cases where you overestimate the background, the best-fit amplitude can still be negative and result in an improvement of the likelihood.

I agree with @cdeil here that the only reasonable way to debug this, is computing and exporting the likelihood profiles. As I wanted to work on the `FluxPointEstimator` class this week anyway, I would volunteer to do this. For this it would be useful to have minimal test case where the flux point computation fails. 

@lmohrmann Could provide me with a minimal test case or analysis notebook where the computation fails?

**Comment by lmohrmann** [comment] 2018-09-18 10:31
@adonath: It's not exactly minimal, but I've send you a notebook by mail (since I couldn't upload it to this issue). Thanks for looking into this!

**Comment by lmohrmann** [comment] 2018-10-01 19:38
@adonath I just had a look a your "Modeling & Fitting" slides from the coding sprint today. Any chance that the problems observed for the minuit backend (i.e. this issue) will also be worked on?

**Comment by adonath** [comment] 2018-10-02 12:09
@lmohrmann I already started to rewrite the `FluxPointEstimator` (mostly simplifying and clean up), but this did not resolve the issue with the high energy points and upper limits yet. I'll plan to have one of the coding sessions at the coding sprint to continue this works and hopefully resolve the issue maybe with pair coding. I'll notify you as soon as we open a PR.

**Comment by cdeil** [comment] 2018-10-03 20:34
Flux point estimator improved by @adonath  in #1851 .

@lmohrmann @bkhelifi - Please re-run with Gammapy master, and if you still find incorrect results in some cases, please comment here.

**Comment by lmohrmann** [comment] 2018-10-04 14:09
@cdeil @adonath I re-ran the analysis with master, and there are still some problems with the flux points (the last ones, where it can e.g. happen that n_on=0). It also happens in the notebook that I sent you, @adonath (the last point is obviously much too high and the two limits before that are also wrong). Let me know if I can do anything else to help track down the problem.

**Comment by cdeil** [comment] 2018-10-04 14:15
@lmohrmann - We are adding a flux point likelihood profile to debug this week: #1854
Suggest you wait a bit while we are working on it this week at the Gammapy coding sprint.

Then from Monday on, @adonath will be on vacation for three weeks and I also won't have time for debugging / coding, so if you then have time to continue debugging or sending PRs with fixes for the spectral points in the coming weeks, that would be great.

Note that in `fermipy/castro.py` there's already some code to use `np.interp1d` on the likelihood profile to compute UL without using something fancy like MINOS. Putting such a method in Gammapy and using it would probably be the way to go.

**Comment by cdeil** [comment] 2018-10-19 12:44
@adonath - I did merge #1854 and the pair-coding we did in Madrid to try to compute the profiles is here: https://github.com/gammapy/gammapy/commit/478411ca3532aa85994e29c6c0c17c7761317d52

I don't have time to continue, I think this requires 2-3 days of coding to do basically a (test-driven?) rewrite of the FluxPointEstimator.

For unknown reasons, this restoring of quality mask doesn't seem to have any effect on the computed flux points, I get the same one when commenting out the line:

https://github.com/gammapy/gammapy/commit/478411ca3532aa85994e29c6c0c17c7761317d52#diff-a0cfec442f4371168c974a2fea1f5260R750

For this point, or generally about filtering or if it's possible to avoid changing the input obs objects, maybe @registerrier - you have an idea?

Just to note what we already discussed: I think hard-coding the parameter name to amplitude is problematic. It probably will give incorrect results for models like ECPL because there amplitude and dnde differ by an energy-dependent factor. And also hard-coding the estimator to minuit isn't a good solution:

https://github.com/gammapy/gammapy/blob/2490b4671c281b261b7b237f939220b789cba5ba/gammapy/spectrum/flux_point.py#L702

If you look in Fermipy you'll see that they compute likelihood profiles themselves and then use scipy for 1D optimisation (best-fit parameters) and root-finding (for parameter errors and upper limits).
That seems reasonable to me, 1D is just a special case; but if the general fitting backend works for this and you just want to do 1D optimisation via that, also OK.

One idea we were discussing is to create a temp spectral model with a few lines that wraps any given spectral model shape, and just has one amplitude parameter at the energy of interest. Then it'll work for any spectral model.

@adonath - If you have time for Gammapy, probably you should make this your priority in November when you're back from vacation. Alternatively, @registerrier or @lmohrmann or anyone with interest and skills on spectral point computation - if you have time and want to work on this in the coming weeks, leave a comment here before you start hacking.

**Comment by adonath** [comment] 2018-11-20 10:20
Addressed by #1929, #1933 and #1934. @bkhelifi  and @lmohrmann please re-run your analyses with the Gammapy dev version or Gammpy 0.9 (will be released later this week) and please open new issues, when you still find problems.

**Closed by adonath** 2018-11-20 10:20 UTC
Labels: bug, question

**Comment by lmohrmann** [comment] 2018-11-29 09:43
Hi @adonath, 
I can confirm that I am now getting the same results as previously!
Many thanks!
