### ISSUE TITLE
Incorrect unit treatment in `make_map_exposure_true_energy` and `MapMaker`

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1436] opened 2018-06-21 10:22 UTC
The unit is not given to the maps created by `make_map_exposure_true_energy`.
Similarly `MapMaker`creates an exposure map without instating its unit. 
This should be corrected.

**Comment by cdeil** [comment] 2018-06-21 10:53
For whoever takes this up: my suggestion would be to add a failing test first, and only then touch the implementation of `MapMaker`.

Note that `make_map_exposure_true_energy` has a test and is giving a good unit:
https://github.com/gammapy/gammapy/blob/34df2927fa897c948949122ab49d87d1f022b719/gammapy/cube/tests/test_new.py#L69
So the problem is in `MapMaker`, because it initialises an exposure map without unit.

The easiest would be to run the same example that se use in `test_new.py` already through `MapMaker` and add the same asserts as we have for the functions, either for all outputs, or just for exposure map for now.

**Comment by cdeil** [comment] 2018-07-06 07:14
Fixed by @AtreyeeS in #1448 .

@registerrier - If something is still to be done, leave a comment what it is and re-open.

**Closed by cdeil** 2018-07-06 07:14 UTC
Labels: bug, effort-low, package-novice
