### ISSUE TITLE
Getting errors for sum of two models

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2147] opened 2019-05-21 12:04 UTC
Suppose we have a sum of two models:

```python3

# two eg models
model1 =SkyGaussian(lon_0=lon1, lat_0=lat1, sigma=sigma1)
model2=SkyGaussian(lon_0=lon2, lat_0=lat2, sigma=sigma2)

#sum model
model_sum = model1 + model2

#... Fit some dataset using model_sum...
fit = Fit(dataset)
result = fit.run(optimize_opts={"print_level": 1})

# Get errors of parameter
result.parameters.error("sigma")
```

This returns only the error on the `sigma` of `model1` and not `model2`. 
Calling by the index instead of parameter name works, ie, `result.parameters.error(5)` will return the error on model2, but this is not very pleasant when there are many parameters from many models.

**Comment by adonath** [comment] 2019-05-21 12:40
Thanks @AtreyeeS for reporting this. I think it's basically a known issue. The problem is of course the ambiguity of the name of the `sigma` parameter, which is present in both models. I think we can only resolve this by introducing model names. So that you can do e.g. `parameters["source_1.sigma"]` or `parameters["source_1"].error("sigma")`. We don't have a clear proposal and solution to this, but I have written some thoughts in the models PIG (see [here](https://github.com/gammapy/gammapy/blob/81d6cfc7f2268a35512c58c46e0924c4b04fed5f/docs/development/pigs/pig-007.rst#introduction-of-model-name-attributes)). In general this is definitely something we should try to sort out for Gammapy v0.13

**Comment by AtreyeeS** [comment] 2019-05-21 13:42
Perhaps a temporary solution could be to have `Parameters._get_idx() return a list instead of a single value, and then `parameters.error("par_name")` can return the errors on all occurrences of the parameter?
But if this is a priority for v0.13, then I think it can wait for a proper implementation as well.

**Comment by adonath** [comment] 2019-07-25 10:19
This issue is still unresolved, but I'll assign @QRemy, because it's also related to model serialisation...

**Comment by QRemy** [comment] 2019-11-29 09:29
Now you can do this:
`pars = model2.parameters
pars.covariance = results_joint.parameters.get_subcovariance(pars)
pars.parameters.error("sigma")`

Then we will add a way to fill the sub-covariance matrix automatically after the fit.

**Comment by adonath** [comment] 2020-07-06 16:19
By now we further improved the API so that errors are directly available on the parameter after the fit, like so:
```
model2.sigma.error
``` 
This does not resolve the problem with the parameter names, but solve the problem with errors. How ever this API is probably not documented well enough...

**Comment by adonath** [comment] 2020-10-06 15:20
Actually the API is documented here: https://docs.gammapy.org/0.17/notebooks/modeling.html#Covariance-and-parameters-errors. Closing the issue now...

**Closed by adonath** 2020-10-06 15:20 UTC
Labels: priority-high, question
