### ISSUE TITLE
Different behaviour of mask_safe for SpectrumDataset and SpectrumDatasetOnOff

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2901] opened 2020-05-19 11:33 UTC
**Gammapy version**
0.17

**Bug description**
It's possible to change the `mask_safe` of a `SpectrumDatasetOnOff` by doing
```
ds.mask_safe.data = new_mask
```
This does not work for a `SpectrumDataset` however.

**Expected behavior**
`SpectrumDataset` and `SpectrumDatasetOnOff` should behave the same way.

**Other information**
`mask_safe` has a `@property` decorator for the `SpectrumDataset`, which prevents changing it. It seems that this is not inherited properly, hence one can change the mask of a `SpectrumDatasetOnOff`.

I guess it makes sense to disallow changing attributes of the `mask_safe`. But then it should also not work for the `SpectrumDatasetOnOff`.

**Comment by lmohrmann** [comment] 2020-05-19 11:53
Incidentally, what _is_ the intended way of setting the `mask_safe`? Something like this?
`ds.mask_safe = RegionNDMap.from_geom(ds.mask_safe.geom, data=new_mask)`

**Comment by registerrier** [comment] 2020-05-19 12:19
Thanks @lmohrmann . 

There is a `setter` property on `SpectrumDataset.mask_safe` but it expects a `RegionNDMap` object and raises an `ValueError` if something else is passed.

So as you quote, the correct usage would be `dataset.mask_safe = my_mask` rather than `dataset.mask_safe.data = my_mask`.

Are you sure there is an inconsistent behavior between `SpectrumDataset` and `SpectrumDatasetOnOff`? If you have an example usage, it would help reproducing it.

**Comment by lmohrmann** [comment] 2020-05-19 12:55
Well, I tried modifying the `mask_safe.data` attribute for either type of spectrum data set, but it had an effect only for the `SpectrumDatasetOnOff`. I can try to construct a minimal working example, but not at the moment. Should be possible to test with any `SpectrumDataset` and `SpectrumDatasetOnOff` I guess.

**Comment by adonath** [comment] 2020-10-01 10:18
I cannot reproduce the issue anymore: 
```python3
from gammapy.datasets import SpectrumDataset, SpectrumDatasetOnOff
from gammapy.maps import MapAxis
import numpy as np

axis = MapAxis.from_energy_bounds("1 TeV", "10 TeV", nbin=11)

dataset = SpectrumDataset.create(e_reco=axis)
print(dataset.mask_safe.data.sum())
dataset.mask_safe.data = np.arange(11)
print(dataset.mask_safe.data.sum())

dataset_on_off = SpectrumDatasetOnOff.create(e_reco=axis)

print(dataset_on_off.mask_safe.data.sum())
dataset_on_off.mask_safe.data = np.arange(11)
print(dataset_on_off.mask_safe.data.sum())
```

Either it was never present or fixed in the meantime. I'll close the issue now.

**Closed by adonath** 2020-10-01 10:18 UTC
Labels: bug
