### ISSUE TITLE
Handling node types in `MapAxis`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2027] opened 2019-02-10 21:59 UTC
This is related to #1967 . I think we should decide (maybe at the upcoming coding sprint?) on a proper handling of `node_types` while we are working on `Datasets`. Currently, we have a very ugly mix of `edge` and `center`. For ex: `MapEvaluator` returns a `npred map` with `node_type = edges`, which is definitely meaningless. This is usually not a problem, but sometimes is serious as in making a diffuse background in the `fermi_lat` tutorial. I have put in a hack for the present, but I am sure this will be completely non-intuitive and extremely confusing to any user. 

Either we should completely remove the functionality to have different node types, and thus all checks like: https://github.com/gammapy/gammapy/blob/87aba48b320b1ff9ca1e2cb1fdd2d19c6451afb0/gammapy/cube/models.py#L364

or we should decide on how to do this correctly.

**Comment by adonath** [comment] 2019-07-25 13:31
I am closing this issue as a duplicate of #1967. Please re-open @AtreyeeS, if you think there is more to discuss here.

**Closed by adonath** 2019-07-25 13:31 UTC
