### ISSUE TITLE
Adding and removing models

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2904] opened 2020-05-22 18:25 UTC
I found some strange behaviour while adding and removing models in the present dev version of gammapy. I try to reproduce a very basic example here.

https://github.com/AtreyeeS/test_notebooks/blob/master/simulate_3d.ipynb

Making the datasets is just using the part from simulate_3d notebook.
In the next section, I (i) add a model, (ii) remove it and (ii) add it back (with some different initial parameters). The `npred` calculation after (iii) goes back to what it was after (i), which is unexpected.

This, of course, leads to the minimiser royally failing later on...

@QRemy @registerrier @luca-giunti - have you faced this before? Any idea what is causing this?

**Comment by adonath** [comment] 2020-05-22 20:12
@AtreyeeS Thanks this was a good catch! The problem is the following:

The model evaluators are cached in the `MapDataset.npred()` in a private `_evaluators` dictionary which uses the model name as keys (see https://github.com/gammapy/gammapy/blob/master/gammapy/datasets/map.py#L249). As the model uses the same name, the previous cached version is used internally. This is indeed a bad behaviour. I guess a quick fix is to use the model id as a key for the `_evaluators` dict instead of the model name. 

In general the issue should be resolved in the context of the global model handling, which we need to settle on a soon as possible. It will be the project with the highest priority, once I'm backgrounders from parental leave in the 2nd week of June

**Closed** 2020-05-26 16:48 UTC
Labels: bug, question
