### ISSUE TITLE
Problem with SpectrumDataset

### ISSUE THREAD

**Issue by Borch33** [gammapy/gammapy#2318] opened 2019-08-12 10:00 UTC
I'm following the tutorial at https://docs.gammapy.org/dev/notebooks/spectrum_simulation.html , but it gives an error on the cell number 10. I used the same commands, a part for the model (I used a TableModel) and the parameters/data (I put mine). The problem is the following:

with the following configuration:
```python
dataset = SpectrumDataset(
aeff=aeff, edisp=edisp, model=model_ref, livetime=livetime, obs_id=0
)
dataset.fake(random_state=42)
```
I get, as error:
```
TypeError: init() got an unexpected keyword argument 'obs_id'
```
with the following configuration:
```python
dataset = SpectrumDataset(
aeff=aeff, edisp=edisp, model=model_ref, livetime=livetime
)
dataset.fake(random_state=42)
```
I get, as error:
```
AttributeError: 'NoneType' object has no attribute 'energy'
```
How can I solve this?

I'm using Gammapy version 0.12

**Comment by Borch33** [comment] 2019-08-12 12:57
Problem solved:
In version 0.12 of Gammapy the SpectrumDataset is defined differently if compared to the one of version 0.13. One should follow the guide in the 0.12 documentation (i.e. using the correct functions/parameters), present in https://docs.gammapy.org/0.12/notebooks/spectrum_simulation.html?highlight=spectrum%20simulations%20cta .

**Comment by adonath** [comment] 2019-08-26 07:48
Thanks @Borch33 for your patience! I was on holiday and could not respond earlier. It seems the problem is resolved by following the (correct) tutorial for v0.12?

Gammapy is currently changing fast, that's why we release every ~2 months. We try to improve and stabilise the API for 1.0, but this also means we have to introduce backwards incompatible changes between the small version numbers, e.g. the one that caused the problem you reported. The best we can do for now is to keep our documentation up-to date and provide good user support, so please let us now any time (e.g. also via [gammapy.slack.com](gammapy.slack.com)), if you need any help.

**Comment by adonath** [comment] 2019-09-26 14:54
@Borch33 Please reopen if you think there is still something to be clarified.

**Closed by adonath** 2019-09-26 14:54 UTC
Labels: bug, question
