### ISSUE TITLE
OFF region determination in SpectrumExtraction  v0.6 -> v0.7

### ISSUE THREAD

**Issue by ctrichard** [gammapy/gammapy#1336] opened 2018-03-05 09:46 UTC
Hi,

I made the same analysis with gammapy v0.6 and v0.7 . I noticed that now many analysis of the DC1 gps data fail because SpectrumExtraction cannot find OFF region in v0.7 while it worked in v0.6.

More details : 
```
...
  on_region = CircleSkyRegion(center=target_position, radius=on_radius)
  bkg_estimator= ReflectedRegionsBackgroundEstimator(
  		    obs_list=obs_list,
		        on_region=on_region,
			    exclusion_mask=exclreg,
			    )
  bkg_estimator.run()
  bkg_estimate = bkg_estimator.result

  extract = SpectrumExtraction(
		    obs_list=obs_list,
		        bkg_estimate=bkg_estimate,
			e_reco=ebounds,
			e_true=ebounds
			)
  extract.run()

  print("observations : ",len(obs_list))
  print("observations : ",len(extract.observations))
```

> obs_list contain non empty list of obs with good offsets. And the mask is the same for analyses with v0.7 and v0.6.
 
For ~800 sources analysed in the gps, I end up with 109 fails in v0.7 while none in v0.6 (by fails I mean len(extract.observations)<1) ...

In my understanding it comes from the fact that no OFF region can be determined (probably due to excluded region). Can you tell me why this changed in v0.7  ?

Thanks,
Cyril.

**Comment by cdeil** [comment] 2018-03-06 13:07
@ctrichard - Please provide a bit more information to help us understand or reproduce the issue.

Are you saying the result with Gammapy 0.7 is incorrect?
Or is it an open question if the result from 0.6 was or 0.7 is incorrect?

What are your version numbers for Astropy and regions?

Is this a change in reflected regions finding? Or in the step after of spectral extraction?
It sounds like the problem is with reflected region finding and no spectral extraction needs to be run to see it?

Ideally: can you narrow down the issue a bit, to the point where you share a script of notebook we can run that reproduces the issue? If we get this, the chances of understanding and fixing the issue quickly are much higher compared to e.g. me starting to write my own scripts / notebooks and looking at reflected regions or spectral extraction, trying to find the issue.

**Comment by ctrichard** [comment] 2018-03-06 17:25
Hi,

Thanks for your answer, sorry for not being clear! Here you have the same analysis done with gammapy  v0.6 and v0.7. 

https://www.cppm.in2p3.fr/~trichard/pro/Gammapy/BkgEstimatorv06.ipynb
https://www.cppm.in2p3.fr/~trichard/pro/Gammapy/BkgEstimatorv07.ipynb

Notice the following differences in the packages versions : 
      " gammapy :  0.6",
      " astropy :  1.3.3",
      " numpy :  1.12.1",
and 
     " gammapy :  0.7",
      " astropy :  3.0",
      " numpy :  1.14.1",
The regions package version is the same in both analyses : 0.2.

I realized that the problem comes from the creation of exclusion regions. In v0.7 there is a problem with one region (see red output in v0.7) and it seems to create a big exclusion preventing to find OFF regions and so there is no correct observations to extract the spectrum... It is visible by the fact that the image from bkgestimator is completely black while it looks ok in v0.6 : 

![capture d ecran de 2018-03-06 18-17-41](https://user-images.githubusercontent.com/10496603/37047274-bb15bd4c-216a-11e8-8449-dca21191abca.png)


You need the following files to run the analysis : 
[files.zip](https://github.com/gammapy/gammapy/files/1785976/files.zip)



Thanks for your help !
Cyril.

**Comment by ctrichard** [comment] 2018-04-24 16:35
Hi @cdeil,
I simplified the notebooke to illustrate the bug.
Please have a look at this notebook :
[Test_regions.zip](https://github.com/gammapy/gammapy/files/1943088/Test_regions.zip)

The third map have a different value (0 instead of 1). This seems to be related to the conversion of fk5 coordinates into a Skyimage defined with galactic coordinate system. But it does not appear for all coordinates (the region 13 do not cause problem while region 14 do).  When creating the mask with the region 14 in galactic coordinates there is no problem ("show_mask_map_fromGALreg")...

I remind you that this problem is present with the latest version of the used packages, but was not with the following version :  
gammapy : 0.6 
astropy : 1.3.3,
numpy : 1.12.1

Thanks,
Cyril.

**Comment by joleroi** [comment] 2018-04-25 07:07
Hi @ctrichard 

Just to make sure we're on the same page: This is what I get with my configuration

```
 gammapy :  0.8.dev5824
 astropy :  3.0.dev20201
 numpy :  1.13.1
 regions :  0.3.dev475
```
**Plot 1**
![plot_1](https://user-images.githubusercontent.com/11678435/39230691-b59ad2ca-4867-11e8-83f4-5fe4d031a33b.png)

**Plot 13**
![plot_13](https://user-images.githubusercontent.com/11678435/39230690-b583689c-4867-11e8-8258-79d32bffd287.png)

**Plot 14**
![plot_14](https://user-images.githubusercontent.com/11678435/39230689-b56c6fe8-4867-11e8-9834-d3c9518e5be3.png)

**Plot 14gal**
![plot_14gal](https://user-images.githubusercontent.com/11678435/39230688-b553530a-4867-11e8-9048-e692c446e355.png)

**Plot 109**
![plot_109](https://user-images.githubusercontent.com/11678435/39230687-b53bd1ee-4867-11e8-8991-86878ebc4f47.png)

Is this what you expect?

**Comment by ctrichard** [comment] 2018-04-25 08:28
It was I obtained, the problem is plot14 should be the same as plot14gal. 

I added several other test to understand what is going on : 

[Test_regions.zip](https://github.com/gammapy/gammapy/files/1946091/Test_regions.zip)

The results depend on the position of the center of the map. I slightly change it and both map are different (see plots : "snr 354 reg 14" and "snr 561 reg 14") even when the region is in the fov.

And for the original test, the result is same also by reducing the fov (see plot "reg 14 small fov " compared to the plot "reg 14")

Thanks !
Cyril

**Comment by joleroi** [comment] 2018-04-25 08:32
A general comment in case you don't know about it: You can make the plots appear in the notebook by adding the [magic command](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-matplotlib) 
```
%matplotlib inline
```
At the beginning of the notebook. That way one does not have to jump between the notebook and the plots.

**Comment by joleroi** [comment] 2018-04-25 08:38
Ah I just see that they somehow appear at the end of your notebook. Sorry I was confused by the
```
if __name__ == "__main__":
```
statement, I don't think you need this, do you?

**Comment by ctrichard** [comment] 2018-04-25 08:47
Yes sorry I forgot about the `%matplotlib inline` but since plots are appearing at the end I was happy^^

`if __name__ == "__main__":` this is a remnant of my script, it is useless for the notebook indeed :).

**Comment by cdeil** [comment] 2018-04-25 08:48
@joleroi @ctrichard - thanks for tracking down this issue!

I'm not sure if pinning down the problem from the example by @ctrichard  is more effective, or to extend the existing tests at https://github.com/gammapy/gammapy/blob/master/gammapy/background/tests/test_reflected.py to add asserts on first and last reflected region position, and to add a test case with a sky image in RADEC instead of GALACTIC frame.

This improvements of the tests (and probably bugfix concerning sky image or region frame handling in the implementation) could be done separately or together with #1391 .
I'll unsubscribe from this issue now; if you want feedback from my, please @ mention me.

**Comment by ctrichard** [comment] 2018-04-25 09:13
@joleroi @cdeil sorry for the spam...
Quick important information, the problem seems to disappear when removing the `proj='TAN'` parameter in the `SkyImage.empty` function...

**Comment by cdeil** [comment] 2018-05-07 15:26
@ctrichard - Thank you for debugging this issue!

Here's the notebook you last showed:
https://nbviewer.jupyter.org/gist/cdeil/cd1862c9096db1731c0c59ad2b72f3d2

So if I understand correctly, you say that the bug is in `SkyImage.region_mask`, not in the reflected region computation?

Could you please try running this example?

```python
from astropy.coordinates import SkyCoord, Angle
import regions
from gammapy.image import SkyImage

image = SkyImage.empty(
    xref=70, yref=3,
    nxpix=600, nypix=600,
    binsz=0.04,
    proj='TAN', coordsys='GAL',
)
print(image.wcs)
region = regions.CircleSkyRegion(
    center=SkyCoord(60, -4, unit='deg', frame='galactic').fk5,
    radius=Angle(1, 'deg'),
)

mask = image.region_mask(region)
mask.data = mask.data.astype(float)
mask.plot()
```

I tried to create a test case for which you say in the notebook that the result you get is incorrect. For me the result OK in this case, and also if I choose different frames for the region center coordinate:
![screen shot 2018-05-07 at 17 23 20](https://user-images.githubusercontent.com/852409/39709882-6402a222-521b-11e8-8ceb-3a015dacaf82.png)

My versions (see [here](https://gist.github.com/cdeil/f22efde16f431fad22f6108dc650248d)) are Gammapy master, regions 0.2 and Astropy 3.0 (Astropy version should be irrelevant, only regions and Gammapy are changing).

**Comment by cdeil** [comment] 2018-05-07 15:36
I tried all kinds of different combinations of frame for the sky image, the pointing center and the region center: http://docs.gammapy.org/dev/background/reflected.html

I always get the same, correct result, i.e. I'm not able to reproduce an incorrect reflected region result.

@ctrichard - Could you please try again and produce a minimal example that gives an incorrect result for you? (using the code I gave in the last comment or from the reflected region docs page as starting point).

**Comment by ctrichard** [comment] 2018-05-08 15:45
Hi @cdeil ,

Thanks for looking into this issue. Indeed I don't think the problem is the reflected background computation.
I have the same results as you for the example you presented in the previous comment.

Can you try this : 

```
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord, Angle
import regions
from gammapy.image import SkyImage
import astropy.units as u
from regions import CircleSkyRegion

lon=68.97601
lat=2.43277
reglon=251.055743
reglat=-45.822014
radius=0.6242692716666667
i=14
fov=5
pixsize=0.04
    
ref_image = SkyImage.empty(
      nxpix=int(100*fov), nypix=int(100*fov), binsz=pixsize,
      xref=lon, yref=lat,
     proj='TAN', coordsys='GAL' )

target_position = SkyCoord(reglon,reglat, unit='deg', frame='fk5')
on_radius = radius * u.deg
reg = CircleSkyRegion(center=target_position, radius=on_radius)

   
exclusion_mask = ref_image.region_mask(reg)
exclusion_mask.data =  1- exclusion_mask.data 
fig = plt.figure(facecolor="white")
exclusion_mask.plot(add_cbar=True)
fig.savefig("Plot_"+str(i)+".png")
plt.show()
```

and then change lon by : 
`lon=69.97601`

I don't have the same results in both cases.


I'm sorry I'm in holidays so I cannot do much more for the moment.

Cheers,
Cyril

**Comment by joleroi** [comment] 2018-06-27 11:45
What's the status here? Anything left to be done?

**Comment by cdeil** [comment] 2018-06-27 12:28
@joleroi - I think making a notebook with the example by @ctrichard in the last comment, and showing / comparing the mask for `lon=68.97601` and `lon=69.97601` should be done. 

It's not clear to me if there's a bug in `ref_image.region_mask` or just a misunderstanding that region selection is pixel-based and changing the ref point with TAN projection can slightly change results.

**Comment by cdeil** [comment] 2018-07-29 15:15
@registerrier - Since you volunteered to do the transition to Map for the reflected region computation (see #1391), I'm assigning this issue to you.

I think I tried to reproduce / understand the issue described by Cyril in the May 8 comment above, but never figured out what the actual issue was, i.e. wan't able to extract a failing regression test case as a first step to fixing this.

@registerrier - Maybe you could have a look at the last comments above (especially the one from May 8) and try to extract a test case before doing #1391 . If you don't manage within an hour, I'd suggest to just go ahead and try to write clean new code and a few good test cases for reflected regions, and then we ask Cyril to re-run. Note that we can always do a v0.8.1 release any time with little effort if some important bug appears after v0.8.

**Comment by cdeil** [comment] 2018-08-02 18:15
@ctrichard - Could you please try your analysis again with Gammapy master, or if you see this later, with Gammapy v0.8 that we plan to release next week?

@registerrier and I were not able to find a bug from the description above.

Note that in #1616 the reflected region was change to use gammapy.maps, and also the ReflectedRegionsFinder was improved a bit. See here:
http://docs.gammapy.org/dev/background/reflected.html

All analysis in Gammapy is now using gammapy.maps, also the reflected regions computation and exclusion mask handling. As we said in https://groups.google.com/forum/#!topic/gammapy/OEMpw-zyDaI we know this is a big transition, and we'd like to help you update your scripts (unless you can stick to Gammapy v0.7). 

An intro tutorial how to work with maps is here: http://docs.gammapy.org/dev/notebooks/intro_maps.html

We're also improving the code / documentation how to make exclusion masks, see e.g. https://github.com/gammapy/gammapy/issues/1612

Please get in touch if you have any questions!

If there's still an issue, please re-open this one, or file a new one (ideally with a minimal test case that we can run showing what you get, and stating what you expect instead).

**Closed by cdeil** 2018-08-02 18:15 UTC
Labels: bug, effort-low, package-intermediate
