### ISSUE TITLE
Broken notebook image_fitting_with_sherpa.ipynb

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1942] opened 2018-11-23 07:59 UTC
```bash
$ gammapy jupyter --src=./tutorials/image_fitting_with_sherpa.ipynb test
AttributeError in cell [12]

--SOURCE CODE: 
%%time
sh.fit()

--TRACEBACK: 
...
...
...
    718         if hasattr(self.kernel, "sky"):
    719             # This corresponds to the case when the kernel is actually a psf image, not just a model.
--> 720             psf_pixel_size = self.kernel.sky.cdelt
    721             data_pixel_size = data.sky.cdelt
    722 

AttributeError: 'NoneType' object has no attribute 'cdelt'
```

This is my config:

```
$ gammapy info

System:

	python_executable      : /Users/jer/anaconda/envs/gammapy-dev/bin/python 
	python_version         : 3.7.0      
	machine                : x86_64     
	system                 : Darwin     


Gammapy package:

	path                   : /Users/jer/git/gammapy/gammapy/gammapy 
	version                : 0.9.dev7875 
	githash                : 9a529c543eb62cac2f7d85ffc898785f923a3c2c 


Other packages:

	numpy                  : 1.15.4     
	scipy                  : 1.1.0      
	matplotlib             : 3.0.2      
	cython                 : 0.29       
	astropy                : 3.0.5      
	astropy_healpix        : 0.3.1      
	reproject              : 0.4        
	sherpa                 : 4.10.1     
	pytest                 : 4.0.0      
	sphinx                 : 1.7.9      
	healpy                 : 1.12.5     
	regions                : 0.3        
	iminuit                : 1.3.3      
	naima                  : 0.8.1      
	uncertainties          : 3.0.3      


Gammapy environment variables:

	GAMMAPY_DATA           : /Users/jer/DATA/GAMMAPY 
	GAMMAPY_EXTRA          : /Users/jer/git/gammapy/gammapy-extra 
	GAMMA_CAT              : /Users/jer/git/gammapy/gamma-cat 
	GAMMAPY_FERMI_LAT_DATA : /Users/jer/git/gammapy/gammapy-fermi-lat-data 
	CTADATA                : /Users/jer/DATA/DC/1dc 
```

**Comment by cdeil** [comment] 2018-11-23 08:05
This is a duplicate of #1905 .

Will be fixed via the next Sherpa release:
https://github.com/sherpa/sherpa/pull/551

@Bultako - Can you mark that notebook as xfail for now for CI? I think it already is?

Otherwise, the idea it to just do nothing and wait for the next Sherpa release.
Let's keep this issue open as a reminder.

**Comment by Bultako** [comment] 2018-11-23 08:13
ok
sorry for this duplicate.
so, nothing to do now.

👍

**Comment by cdeil** [comment] 2018-12-20 16:37
This issue was solved in https://github.com/sherpa/sherpa/releases/tag/4.10.2

I see the issue locally with Sherpa 4.10.1, and when I update to 4.10.2, it's resolved.
```
conda update sherpa -c sherpa
gammapy jupyter --src=./tutorials/image_fitting_with_sherpa.ipynb test
```
Closing.

**Closed by cdeil** 2018-12-20 16:37 UTC
Labels: bug
