### ISSUE TITLE
IACTBasicImageEstimator: empty values in PSF at large offset/low E 

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy#1143] opened 2017-09-20 14:52 UTC
When creating excess maps with IACTBasicImageEstimator and the RingBackgroundEstimator, the code crashes when using large offset observations (>3.5°) and low energies (<200 GeV) in the spline of the PSF. This might be due to the fact that the PSF is not defined (zero values) in the IRFs for this range of parameters.

A minimal example is shown here 
https://github.com/facero/share/blob/master/test-offset-crash.ipynb

**Comment by adonath** [comment] 2017-09-22 11:45
Thanks for reporting this bug! Can you confirm the issue is resolved by https://github.com/gammapy/gammapy/pull/1150?

**Comment by facero** [comment] 2017-09-22 12:46
I've run the test case again with #1150 and played with a range of parameters and the issue is resolved ! Thx

**Comment by adonath** [comment] 2017-09-22 16:44
Fixed by #1150.

**Closed by adonath** 2017-09-22 16:44 UTC
Labels: bug
