### ISSUE TITLE
Notebook sed_fitting_gammacat_fermi broken

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1778] opened 2018-09-10 15:06 UTC
It seems the `par_000_index` keyword in options for `minuit`is not allowed?

<pre>
RuntimeError in cell [19]

--SOURCE CODE: 
result_log_parabola = fitter.run(flux_points, log_parabola)
print(result_log_parabola["best-fit-model"])

--TRACEBACK: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-62d174956f10> in <module>()
----> 1 result_log_parabola = fitter.run(flux_points, log_parabola)
      2 print(result_log_parabola["best-fit-model"])

~/git/gammapy/gammapy/spectrum/flux_point.py in run(self, data, model)
   1019             Dictionary with fit results and debug output.
   1020         """
-> 1021         best_fit_model = self.fit(data, model)
   1022         statval = self.stat(data, best_fit_model)[0]
   1023 

~/git/gammapy/gammapy/spectrum/flux_point.py in fit(self, data, model)
    997                 parameters=model.parameters,
    998                 function=total_stat,
--> 999                 opts_minuit=p["opts_minuit"],
   1000             )
   1001             self._minuit = minuit

~/git/gammapy/gammapy/utils/fitting/iminuit.py in fit_iminuit(parameters, function, opts_minuit)
     48 
     49     parnames = _make_parnames(parameters)
---> 50     minuit = Minuit(minuit_func.fcn, forced_parameters=parnames, **opts_minuit)
     51 
     52     minuit.migrad()

iminuit/_libiminuit.pyx in iminuit._libiminuit.Minuit.__init__()

iminuit/_libiminuit.pyx in iminuit._libiminuit.check_extra_args()

RuntimeError: Cannot understand keyword par_000_index. May be a typo?
The parameters are ['par_000_amplitude', 'par_001_reference', 'par_002_alpha', 'par_003_beta']
INFO:gammapy.scripts.jupyter:   ... TESTING /Users/jer/git/gammapy-extra/notebooks/simulate_3d.ipynb
</pre>

**Comment by cdeil** [comment] 2018-09-10 18:37
@Bultako - Thank you for catching and reporting this issue. That's an important one.

First time I ran the notebook I didn't get the error, second time I ran it I got it. That part I don't understand yet.

But I think I understand what the bug is:
* If `FluxPointFitter` is passed a dict for `opts_minuit` to `__init__`, it stores it in `self.parameters['opts_minuit']`
* The notebook uses the same fitter instance for multiple fits
* When `fitter.fit` is called, it passes `opts_minuit=p["opts_minuit"]` to `fit_iminuit`
* `fit_iminuit` adds things like `par_000_index` to the dict
* Those dict entries from previous runs hang around for the next fit, and then the issue occurs.

I think the changes we should make here are:
* `FluxPointFitter` should be simplified, work like the other fit classed (especially MapFit). It's not supposed to be used for multiple fits and store a lot of state. Also at first I thought the problem was with the function `total_stat` that's nested in `fit`- that's unnecessarily complex, IMO we shouldn't use closures in Gammapy.
* `fit_iminuit` shouldn't modify the input `opts_minuit` dict. Start by making a copy.

@adonath - Do you agree or would you suggest some other changes?

Since these are a bit complex pieces of code, maybe we resolve this issue with pair coding tomorrow?

**Comment by Bultako** [comment] 2018-09-10 19:01
I've had a look at the code.
I think the error is related with the `index` suffix in the `par_000_index` keyword. Though I easily found that the other suffix (`amplitude`, `reference`, `alpha`,` beta`) came from the params of the model, I did not understand why we do have `index` in the list of suffix to build the option-list for `minuit`.

My 2 cents..

**Comment by adonath** [comment] 2018-09-11 08:34
@cdeil I agree 100% with your second suggestion, that we should never modify inputs at all in Gammapy. I think this is what causes the issue here. I'll take a closer look and fix it now...

I don't agree with your first suggestion. The complexity in the `FluxPointFitter` arose, when I changed it to the `Minuit` fitting back-end, because two coding styles clashed. The `FluxPointFitter` was designed to **not** hold an internal state and to **be reusable** for multiple fits (so exactly the contrary of what you said). I intentionally decoupled the data and model from the fitter to make it reusable, which makes totally sense for its use case, because you typically fit a few models and check which one fits best. This way you don't carry 6 fitter objects but 6 result objects, which can be used to make the model comparison. The fit state is completely stored in the best fit model (parameters and covariance) and the corresponding fit result dict, which stores meta information such as fit success, number of function evaluations and total stat. If you stick with this concept it is very simple and clean as well. But I think we're opening a much larger question of API design here, that we can't resolve quickly. It will require a future PIG and a few weeks of work to make this consistent in Gammapy anyway.

**Comment by cdeil** [comment] 2018-09-11 10:34
@adonath - My suggestion would still be to change 

http://docs.gammapy.org/dev/api/gammapy.spectrum.FluxPointFitter.html

to be more like 

http://docs.gammapy.org/dev/api/gammapy.cube.MapFit.html
http://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumFit.html

Specifically small changes:

- rename to `FluxPointFit`. I know "fitter" might be the better name, but IMO "fit" also makes sense, because it's not just doing the fit, it also has the likelihood function associated.

- take `opts_minuit` in run, not `__init__`

- remove `run` and just do that in fit alwyas, it's super cheap.

- don't copy the input model.

And I would also suggest to take the data and model on init instead of in run, for consistency with MapFit.

But if you really think this is the wrong way to do it and would prefer to change MapFit to be more like how FluxPointFitter is now, then just leave as-is for v0.8 and we'll discuss in the coming weeks.

**Comment by cdeil** [comment] 2018-09-11 10:35
Looking at http://docs.gammapy.org/dev/api/gammapy.spectrum.FluxPointFitter.html I see `opts_minuit` missing in the parameter list for init, and `data` missing in the parameter list for `fit`. Whatever you choose: docstrings should be consistent with signature.

**Comment by cdeil** [comment] 2018-09-11 10:36
Another quick win: http://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumFit.html ha in the class docstring a link to a high-level example. Adding a similar link to the notebook totrial for MapFit and FluxPointFit would be very useful as well.

**Comment by cdeil** [comment] 2018-09-11 10:41
Taking `method : {‘iminuit’}` in `SpectrumFit.__init__`, but `opts_minuit=None` in `SpectrumFit.fit` doesn't make much sense IMO, from an API standpoint, but also there's nothing done with `method` in init in `SpectrumFit` (I hope).
Really a nice change would be to just take an `opts` dict in `fit`, and to move the "method" or "backend" option in there. That would be a big step (but very small code change) towards allowing a uniform fit API that dispatches options to multiple backends.

@adonath - Go as far as you like here, and then maybe tonight I do a follow-up PR if you don't have time for this change.

**Comment by cdeil** [comment] 2018-09-11 17:28
Fixed by @adonath in #1782.

**Closed by cdeil** 2018-09-11 17:28 UTC
Labels: bug
