### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1244] opened 2018-01-10 10:41 UTC
When executing `pip install . ` in a fresh virtual environment on the latest master ( 904e9ab) I get an error message while installing regions.

Heres the full error output:

```
→ pip install .                                                                                                                                    (env: gammapy_installation_test) 
Processing /Users/mackaiver/Development/gammapy
Collecting numpy>=1.8 (from gammapy==0.7.dev5398)
  Using cached numpy-1.14.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting astropy>=1.3 (from gammapy==0.7.dev5398)
  Using cached astropy-2.0.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting regions (from gammapy==0.7.dev5398)
  Using cached regions-0.2.tar.gz
Collecting click (from gammapy==0.7.dev5398)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting pytest>=2.8 (from astropy>=1.3->gammapy==0.7.dev5398)
  Using cached pytest-3.3.2-py2.py3-none-any.whl
Collecting attrs>=17.2.0 (from pytest>=2.8->astropy>=1.3->gammapy==0.7.dev5398)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest>=2.8->astropy>=1.3->gammapy==0.7.dev5398)
Requirement already satisfied: six>=1.10.0 in /Users/mackaiver/.virtualenvs/gammapy_installation_test/lib/python3.6/site-packages (from pytest>=2.8->astropy>=1.3->gammapy==0.7.dev5398)
Requirement already satisfied: setuptools in /Users/mackaiver/.virtualenvs/gammapy_installation_test/lib/python3.6/site-packages (from pytest>=2.8->astropy>=1.3->gammapy==0.7.dev5398)
Collecting py>=1.5.0 (from pytest>=2.8->astropy>=1.3->gammapy==0.7.dev5398)
  Using cached py-1.5.2-py2.py3-none-any.whl
Building wheels for collected packages: regions
  Running setup.py bdist_wheel for regions ... error
  Complete output from command /Users/mackaiver/.virtualenvs/gammapy_installation_test/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/f7/0gb0xhf52fs9s1114ywnpv_m0000gn/T/pip-build-h7m_tqxx/regions/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/f7/0gb0xhf52fs9s1114ywnpv_m0000gn/T/tmp_dlyjh_bpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.13-x86_64-3.6
  creating build/lib.macosx-10.13-x86_64-3.6/regions
  copying regions/conftest.py -> build/lib.macosx-10.13-x86_64-3.6/regions
  copying regions/version.py -> build/lib.macosx-10.13-x86_64-3.6/regions
  copying regions/_astropy_init.py -> build/lib.macosx-10.13-x86_64-3.6/regions
  copying regions/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions
  copying regions/cython_version.py -> build/lib.macosx-10.13-x86_64-3.6/regions
  creating build/lib.macosx-10.13-x86_64-3.6/regions/_utils
  copying regions/_utils/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_utils
  copying regions/_utils/examples.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_utils
  copying regions/_utils/wcs_helpers.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_utils
  creating build/lib.macosx-10.13-x86_64-3.6/regions/core
  copying regions/core/mask.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core
  copying regions/core/pixcoord.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core
  copying regions/core/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core
  copying regions/core/core.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core
  copying regions/core/compound.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core
  copying regions/core/bounding_box.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core
  creating build/lib.macosx-10.13-x86_64-3.6/regions/io
  copying regions/io/read_ds9.py -> build/lib.macosx-10.13-x86_64-3.6/regions/io
  copying regions/io/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/io
  copying regions/io/setup_package.py -> build/lib.macosx-10.13-x86_64-3.6/regions/io
  copying regions/io/write_ds9.py -> build/lib.macosx-10.13-x86_64-3.6/regions/io
  creating build/lib.macosx-10.13-x86_64-3.6/regions/tests
  copying regions/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/tests
  copying regions/tests/setup_package.py -> build/lib.macosx-10.13-x86_64-3.6/regions/tests
  creating build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/circle.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/polygon.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/point.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/rectangle.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/ellipse.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  copying regions/shapes/setup_package.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes
  creating build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/rotate_polygon.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  creating build/lib.macosx-10.13-x86_64-3.6/regions/_utils/tests
  copying regions/_utils/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_utils/tests
  copying regions/_utils/tests/test_examples.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_utils/tests
  creating build/lib.macosx-10.13-x86_64-3.6/regions/core/tests
  copying regions/core/tests/test_bounding_box.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core/tests
  copying regions/core/tests/test_pixcoord.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core/tests
  copying regions/core/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core/tests
  copying regions/core/tests/test_compound.py -> build/lib.macosx-10.13-x86_64-3.6/regions/core/tests
  creating build/lib.macosx-10.13-x86_64-3.6/regions/io/tests
  copying regions/io/tests/test_ds9_language.py -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests
  copying regions/io/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests
  creating build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_rectangle.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_point.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_masks.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_polygon.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/utils.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_circle.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_api.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/test_ellipse.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  copying regions/shapes/tests/setup_package.py -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests
  creating build/lib.macosx-10.13-x86_64-3.6/regions/_geometry/tests
  copying regions/_geometry/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry/tests
  copying regions/_geometry/tests/test_elliptical_overlap_grid.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry/tests
  copying regions/_geometry/tests/test_circular_overlap_grid.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry/tests
  copying regions/_geometry/tests/test_rectangular_overlap_grid.py -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry/tests
  copying regions/_compiler.c -> build/lib.macosx-10.13-x86_64-3.6/regions
  copying regions/_geometry/rectangular_overlap.c -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/pnpoly.c -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/elliptical_overlap.c -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/core.c -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/circular_overlap.c -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/_geometry/polygonal_overlap.c -> build/lib.macosx-10.13-x86_64-3.6/regions/_geometry
  copying regions/tests/coveragerc -> build/lib.macosx-10.13-x86_64-3.6/regions/tests
  creating build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk4.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.physical.windows.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.linear.wcsd.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.fk5.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.linear.wcsp.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.image.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.galactic.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/galactic_reference.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.linear.wcsc.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk5.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.ecliptic.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.fk4.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.color.spaces.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.linear.wcsa.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.icrs.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.color.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.galactic.hms.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk4.hms.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.icrs.hms.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.icrs.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.icrs.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.ecliptic.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.image.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/fk5_reference.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fits.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.ecliptic.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.composite.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.galactic.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/physical_reference.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk4.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.ecliptic.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.galactic.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.icrs.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.ecliptic.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.galactic.hms.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.comment.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk5.hms.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.physical.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.linear.wcs.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.ecliptic.hms.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.physical.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk5.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.galactic.strip.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.physical.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.image.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.icrs.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.linear.wcsi.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk5.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.fk4.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.mosaic.fk5.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  copying regions/io/tests/data/ds9.fk4.reg -> build/lib.macosx-10.13-x86_64-3.6/regions/io/tests/data
  creating build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_circ-mode_exact.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_elli-mode_subpixels-subpixels_1.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_poly-mode_subpixels-subpixels_18.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_elli-mode_subpixels-subpixels_5.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_circ-mode_subpixels-subpixels_1.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_rect-mode_center.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_circ-mode_subpixels-subpixels_5.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_rect-mode_subpixels-subpixels_18.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_circ-mode_subpixels-subpixels_18.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_circ-mode_center.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_elli-mode_center.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_elli-mode_subpixels-subpixels_18.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_rect-mode_subpixels-subpixels_1.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_poly-mode_subpixels-subpixels_1.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_poly-mode_center.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_poly-mode_subpixels-subpixels_5.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_rect-mode_subpixels-subpixels_5.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  copying regions/shapes/tests/reference/test_to_mask_elli-mode_exact.txt -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/reference
  creating build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/data
  copying regions/shapes/tests/data/example_header.fits -> build/lib.macosx-10.13-x86_64-3.6/regions/shapes/tests/data
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/f7/0gb0xhf52fs9s1114ywnpv_m0000gn/T/pip-build-h7m_tqxx/regions/setup.py", line 128, in <module>
      **package_info
    File "/Users/mackaiver/.virtualenvs/gammapy_installation_test/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/mackaiver/.virtualenvs/gammapy_installation_test/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/f7/0gb0xhf52fs9s1114ywnpv_m0000gn/T/pip-build-h7m_tqxx/regions/astropy_helpers/astropy_helpers/commands/build_ext.py", line 290, in run
      np_include = get_numpy_include_path()
    File "/private/var/folders/f7/0gb0xhf52fs9s1114ywnpv_m0000gn/T/pip-build-h7m_tqxx/regions/astropy_helpers/astropy_helpers/utils.py", line 88, in get_numpy_include_path
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  
  ----------------------------------------
  Failed building wheel for regions
  Running setup.py clean for regions
Failed to build regions
Installing collected packages: numpy, attrs, pluggy, py, pytest, astropy, regions, click, gammapy

```

**Comment by cdeil** [comment] 2018-01-10 12:16
Presumably you get the same error if you just `pip install regions` in a fresh venv?

I'm not an expert in setuptools / pip, but my understanding is that their dependency resolution is only being worked on now. So I'm not surprised that `pip` doesn't figure out properly that it needs to install `numpy` before attempting to install `regions`, even if `regions` lists `astropy` in `install_requires`, and `astropy` lists `numpy` in all the `*requires` fields:
https://github.com/astropy/astropy/blob/88a5f144b155092dbd2c461ffa22d6cb25d87e5f/setup.py#L90

@mackaiver - I think the best way to fix this is to add 'numpy' as a dependency of regions by adding it to this line:
https://github.com/astropy/regions/blob/12a4a566fddd7ec116d62ff3f7a3e9ba1cbe8e40/setup.py#L109
Do you have time to send a pull request to the regions repo for this or should I?

**Comment by mackaiver** [comment] 2018-01-10 13:08
> I'm not an expert in setuptools / pip, but my understanding is that their dependency resolution is only being worked on now.

I don't think that's the problem.  In fact it does install numpy first. Also when installing regions from the master branch (and not from pypi) it works. So maybe update the version on pypi?

**Comment by cdeil** [comment] 2018-01-10 13:26
I can't reproduce the issue. Can you please try `pip install regions` in a fresh and and report if you get the same error? And also please try `pip install numpy; pip install regions` in a fresh env and report if that still gives you the same error or if installing numpy first resolves it?

Independent of the outcome of this, I should probably cut a new release for `regions` very soon (see https://github.com/astropy/regions/issues/125). But preferably without remaining or new install issues. I still think adding `numpy` to `install_requires` in regions is a good idea, to avoid errors from cases where pip tries to run setup or build for regions without first installing numpy.

**Comment by mackaiver** [comment] 2018-01-11 10:30
> . I still think adding numpy to install_requires in regions is a good idea, to avoid errors from cases where pip tries to run setup or build for regions without first installing numpy.

pip will always install numpy before installing regions. It will however not copy the module  before calling setup.py for regions. Maybe adding numpy to `setup_requires` instead of `install_requires` can help. But as I said the current master branch seems to install just fine.

**Comment by cdeil** [comment] 2018-01-11 10:41
> pip will always install numpy before installing regions. It will however not copy the module before calling setup.py for regions.

I think we just have a different opinion of what "install numpy" means. From your build log I see
```
Running setup.py bdist_wheel for regions ... error
```
and to me that is the first part of installing regions, and I still think it fails because numpy is not installed yet (the numpy wheel has just been fetched, it hasn't been installed yet).

> Maybe adding numpy to setup_requires instead of install_requires can help.

This is what the Astropy setup.py does. I'll make a PR now for `regions` proposing to do the same.

> But as I said the current master branch seems to install just fine.

OK, but for unknown reasons. The problem could just re-appear for someone with a different pip version, or installing a different package that depends on regions, in cases where pip decides to install regions before numpy.

**Comment by cdeil** [comment] 2018-01-11 11:02
I've opened https://github.com/astropy/regions/pull/153 . I'm closing this issue now, nothing to do in the Gammapy repo, suggest to continue the discussion there.

**Closed by cdeil** 2018-01-11 11:02 UTC
Labels: bug, move upstream
