### ISSUE TITLE
Creating a gammapy env using conda

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1832] opened 2018-09-24 15:51 UTC
Hi all,

I have followed the [documentation](http://docs.gammapy.org/dev/getting-started.html#install) and tried to install a fresh version of gammapy under ubuntu and conda 4.5.11. I have unfortunately a crash:

```
[4:37pm] /home/bruno/MesProgrammes> curl -O http://gammapy.org/download/install/gammapy-0.8-environment.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   656  100   656    0     0   2877      0 --:--:-- --:--:-- --:--:--  2877
[4:38pm] /home/bruno/MesProgrammes> conda env create -f gammapy-0.8-environment.yml
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib==2.2.3 -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> sqlite[version='>=3.24.0,<4.0a0'] -> readline[version='>=7.0,<8.0a0'] -> ncurses[version='>=6.1,<6.2.0a0']
  - matplotlib==2.2.3 -> tk[version='8.6.*,>=8.6.7,<8.7.0a0']
  - python==3.6
Use "conda info <package>" to see the dependencies for each package.
```

Have you encountered this issue? The output of the command 'conda info matplotlib==2.2.3' is given here:
```
[4:43pm] /home/bruno/MesProgrammes/gammapy/gammapy> conda info matplotlib==2.2.3

matplotlib 2.2.3 py35hb69df0a_0
-------------------------------
file name   : matplotlib-2.2.3-py35hb69df0a_0.tar.bz2
name        : matplotlib
version     : 2.2.3
build string: py35hb69df0a_0
build number: 0
channel     : https://repo.anaconda.com/pkgs/main/linux-64
size        : 6.7 MB
arch        : None
constrains  : ()
license     : PSF-based
license_family: PSF
md5         : 6d6e786bdb82b24950e8e0ee123acb9a
platform    : None
subdir      : linux-64
timestamp   : 1534273740421
url         : https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-2.2.3-py35hb69df0a_0.tar.bz2
dependencies:
    cycler >=0.10
    freetype >=2.9.1,<3.0a0
    icu >=58.2,<59.0a0
    kiwisolver
    libgcc-ng >=7.2.0
    libpng >=1.6.34,<1.7.0a0
    libstdcxx-ng >=7.2.0
    numpy
    pyparsing
    pyqt 5.9.*
    python >=3.5,<3.6.0a0
    python-dateutil
    pytz
    setuptools
    tk 8.6.*
    tk >=8.6.7,<8.7.0a0
    tornado
    zlib >=1.2.11,<1.3.0a0

matplotlib 2.2.3 py27hb69df0a_0
-------------------------------
file name   : matplotlib-2.2.3-py27hb69df0a_0.tar.bz2
name        : matplotlib
version     : 2.2.3
build string: py27hb69df0a_0
build number: 0
channel     : https://repo.anaconda.com/pkgs/main/linux-64
size        : 6.5 MB
arch        : None
constrains  : ()
license     : PSF-based
license_family: PSF
md5         : 5c32641e48b1a3efb40dd797c5691943
platform    : None
subdir      : linux-64
timestamp   : 1534273730171
url         : https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-2.2.3-py27hb69df0a_0.tar.bz2
dependencies:
    backports.functools_lru_cache
    cycler >=0.10
    freetype >=2.9.1,<3.0a0
    functools32
    icu >=58.2,<59.0a0
    kiwisolver
    libgcc-ng >=7.2.0
    libpng >=1.6.34,<1.7.0a0
    libstdcxx-ng >=7.2.0
    numpy
    pyparsing
    pyqt 5.9.*
    python >=2.7,<2.8.0a0
    python-dateutil
    pytz
    setuptools
    subprocess32
    tk 8.6.*
    tk >=8.6.7,<8.7.0a0
    tornado
    zlib >=1.2.11,<1.3.0a0

matplotlib 2.2.3 py37hb69df0a_0
-------------------------------
file name   : matplotlib-2.2.3-py37hb69df0a_0.tar.bz2
name        : matplotlib
version     : 2.2.3
build string: py37hb69df0a_0
build number: 0
channel     : https://repo.anaconda.com/pkgs/main/linux-64
size        : 6.6 MB
arch        : None
constrains  : ()
license     : PSF-based
license_family: PSF
md5         : a4fa9d10f491522f15789ba6707fce4f
platform    : None
subdir      : linux-64
timestamp   : 1534273737662
url         : https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-2.2.3-py37hb69df0a_0.tar.bz2
dependencies:
    cycler >=0.10
    freetype >=2.9.1,<3.0a0
    icu >=58.2,<59.0a0
    kiwisolver
    libgcc-ng >=7.2.0
    libpng >=1.6.34,<1.7.0a0
    libstdcxx-ng >=7.2.0
    numpy
    pyparsing
    pyqt 5.9.*
    python >=3.7,<3.8.0a0
    python-dateutil
    pytz
    setuptools
    tk 8.6.*
    tk >=8.6.7,<8.7.0a0
    tornado
    zlib >=1.2.11,<1.3.0a0

matplotlib 2.2.3 py36hb69df0a_0
-------------------------------
file name   : matplotlib-2.2.3-py36hb69df0a_0.tar.bz2
name        : matplotlib
version     : 2.2.3
build string: py36hb69df0a_0
build number: 0
channel     : https://repo.anaconda.com/pkgs/main/linux-64
size        : 6.6 MB
arch        : None
constrains  : ()
license     : PSF-based
license_family: PSF
md5         : b52690dbd6940b4c1ba3b8c1ef7ed979
platform    : None
subdir      : linux-64
timestamp   : 1534273679230
url         : https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-2.2.3-py36hb69df0a_0.tar.bz2
dependencies:
    cycler >=0.10
    freetype >=2.9.1,<3.0a0
    icu >=58.2,<59.0a0
    kiwisolver
    libgcc-ng >=7.2.0
    libpng >=1.6.34,<1.7.0a0
    libstdcxx-ng >=7.2.0
    numpy
    pyparsing
    pyqt 5.9.*
    python >=3.6,<3.7.0a0
    python-dateutil
    pytz
    setuptools
    tk 8.6.*
    tk >=8.6.7,<8.7.0a0
    tornado
    zlib >=1.2.11,<1.3.0a0
```

Cheers,
Bruno

**Comment by cdeil** [comment] 2018-09-24 16:09
@adonath @Bultako - Thoughts?

I don't know, would ask on astropy-dev or one of the conda support channels for advice.

Anyone interested to become our conda expert and look into why `UnsatisfiableError` such as this one occur and how to avoid it?

**Comment by Bultako** [comment] 2018-09-24 16:35
I'm afraid we should give an environment-0.8.yml file without pinned versions, only the gammapy version pinned :( 

Reproducible environments with conda, too good to be true...

**Comment by cdeil** [comment] 2018-09-24 17:26
+1 to change to non-pinned conda envs for now. So do we edit the env files in-place? To fix the JSON decode issue we will need a v0.8.1 release. Will we make separate env files for that or do we update the existing one to 0.8.1 via a stealth update, keeping the filename and "gammapy-0.8" name?

For me, the stealth update sounds appealing, but I think it will bite us and cause a lot of confusion. So work towards v0.8.1 and aim for tomorrow or later this week if more issues are reported?

(Long-term: I wouldn't give up on this just yet, we haven't even understood why the issue occurs or asked on the conda mailing list for advice yet)

**Comment by Bultako** [comment] 2018-09-24 17:53
I would modify the file in-place.

@cdeil 
Will `gamapy.version.release` be True for  `v0.8.1` ?
If not I will have to change the code in `gammapy download` to download the read the tutorials YAML file from *web* repo, instead of *gammapy* repo used for dev versions of Gammapy installed.

**Comment by cdeil** [comment] 2018-09-24 18:16
> Will gamapy.version.release be True for v0.8.1 ?

Yes. (I checked this locally just to be 100% sure)

**Comment by jlenain** [comment] 2018-09-26 13:06
Hi,

Same issue as @bkhelifi here, also running with conda 4.5.11 under Ubuntu 18.04.

@adonath, I confirm that forcing matplotlib to version `2.1.1` solves this.
So @Bultako and @cdeil , maybe back to reproducible conda envs  ?

**Comment by cdeil** [comment] 2018-09-26 13:12
@adonath - Where did the `matplotlib=2.1.1` version come from? Maybe put `matplotlib>=2`?
Let's discuss this briefly and decide in the call on Friday.

Of course more user feedback is important here. @jlenain - Thanks!

**Comment by Bultako** [comment] 2018-09-26 13:34
I can tell you why I pushed for MPL 2.2.3 
Fixing to this version in Travis solved regression tests in notebooks

I have freed the version number in last commit in `.travis.yml` and those erros are back
https://travis-ci.org/gammapy/gammapy/jobs/433358100#L1393

Obviously, I prefer having a working user environment to tests passing in Travis CI :)

**Comment by adonath** [comment] 2018-09-26 13:55
@cdeil The `matplotlib=2.1.1` version is the one I get by conda, when I don't force the version number. 

@Bultako Any idea why we see this Travis-CI fails only for notebooks? Because most of our `.plot()` are regularly tested...

**Comment by adonath** [comment] 2018-09-26 14:02
Answering to myself here: it seems the `%matplotlib inline` option calls somewhere to matplotlib's `tight_layout`, which in turn calls to `get_tightbbox()`, where we see the fail in Travis-CI.

**Comment by cdeil** [comment] 2018-09-27 12:42
Another example of matplotlib install failing, from running https://github.com/gammasky/joint-crab/blob/master/Dockerfile where I also put the Gammapy 0.8 env, i.e.
```
  - matplotlib==2.2.3
``
https://github.com/gammasky/joint-crab/blob/46cb2df1673fd7f249fbeaa32f00ff0fd8986b80/environment.yml#L27
```
Step 13/19 : RUN conda env create -f environment.yml
 ---> Running in 18c6f963f530
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib==2.2.3 -> functools32 -> python=2.7 -> ncurses[version='>=6.1,<6.2.0a0']
  - matplotlib==2.2.3 -> functools32 -> python=2.7 -> readline[version='>=7.0,<8.0a0']
  - matplotlib==2.2.3 -> functools32 -> python=2.7 -> sqlite[version='>=3.24.0,<4.0a0']
  - matplotlib==2.2.3 -> functools32 -> python=2.7 -> tk[version='>=8.6.8,<8.7.0a0']
  - python==3.6
Use "conda info <package>" to see the dependencies for each package.
```

I've taken a decision here and changed the existing env to `matplotlib>=2.0`:
https://github.com/gammapy/gammapy-webpage/commit/c4aa9f12da390d862ab0fa4c9bdf6f6adc20790e
That's not nice on the one hand, to change after release.
But the idea of having the env separate was always that we could change it after tagging the release and some integration testing, it's just that at the moment this is done via user testing.

The plan for the v0.8.1 release is then after the coding sprint next week, where we'll get some more testing and fixes presumably.

**Comment by Bultako** [comment] 2018-09-27 15:44
@cdeil 

..and surprisingly the Dockerfile for Binder had built correctly with MPL2.2.3

<img width="1074" alt="captura de pantalla 2018-09-27 a las 17 43 09" src="https://user-images.githubusercontent.com/328261/46157808-db8d3d80-c27c-11e8-93c4-ded02c408b56.png">

The main difference being in Binder we install the conda packages one-by-one in the default conda env with `conda install', while in joint-crab we do a `conda env create -f`

**Comment by adonath** [comment] 2018-09-27 16:14
@Bultako I guess when you install packages one by one, `conda` also downgrades certain packages if there are incompatibilities. Did you check the log file?

**Comment by Bultako** [comment] 2018-09-27 19:27
> We could end up with cases where while having no issues in creating an environment, this one will throws errors when plotting in notebooks

FYI
good news
errors not found in notebooks with the env provided now: `python==3.6` + `matplotlib>=2.0`

**Comment by cdeil** [comment] 2018-10-12 07:12
I think this issue was fully resolved by putting `matplotlib>=2,<3`, I think now it works for everyone.

Closing.


If similar issues appear in the future, we could just have less, strict, more fuzzy version requirements, e.g. conda  allows to put `numpy=1.11` which will match any of `1.11.0`, `1.11.1`, ...
Maybe something to keep in mind when crafting the conda env for the next Gammapy release.

**Closed by cdeil** 2018-10-12 07:12 UTC
Labels: bug
