### ISSUE TITLE
Consistent background FITS column names

### ISSUE THREAD

**Issue by TarekHC** [gammapy/gammapy#987] opened 2017-04-25 08:58 UTC
Hi all, 

These days I have been trying to generate MAGIC DL3 data, and now we are able to import event lists + IRFs quite decently. While doing this, I found some inconsistencies between the [DL3 specifications](http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html) and the gammapy readers.

I'm not even sure if these classes are being used... So correct me if I'm wrong, but:
* Within background/fov_cube.py, "define_scheme" function, the background rate column is called (and read) with the string ``'Bgd'``.
* Within the background/models.py, the "EnergyOffsetBackgroundModel" reads the offset dependent (2D) backgound with the string ``bkg``.
* In the open DL3 specifications, the keyword ``BKG`` is used.

Would it be possible to correct this in the next HESS DL3 production (which I assume is the main issue), and then correct gammapy readers?

Cheers, 

Tarek

**Comment by cdeil** [comment] 2017-04-25 09:08
@TarekHC - Thanks for the issue. Yes, we need to clean this up.

For the 3D background, our thinking was that we throw away the very old class we have and rewrite it using NDDataArray. This needs to happen very soon anyways (also for CTA 1DC) and is the task in 
#947.

**Comment by TarekHC** [comment] 2017-04-25 09:10
@cdeil , what about the 2D background? For a simple 1D analysis it may turn out useful (although of course it can be re-calculated within gammapy).

**Comment by cdeil** [comment] 2017-04-25 09:25
Do you mean the column name should be "BKG" (upper case)?
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-2d

For a very quick look, I don't see where the problem is:
https://github.com/gammapy/gammapy/blob/master/gammapy/background/energy_offset_array.py

Could you please make a "magic" folder in
https://github.com/gammapy/gammapy-extra/tree/master/test_datasets
and put example IRF files for one run there?
Adding a test to read and evaluate those IRFs will make it much easier to get things to work, and even more importantly, to make sure we don't break things as we refactor code in Gammapy.
If privacy is a concern, you can just put *no* events, or just put an events file with the first 10 events from a single run (so that there's no signal).
This is just about supporting the MAGIC file formats and to make sure it keeps working via continuous integration, the goal here is not to run an analysis with a signal on those files.

**Comment by TarekHC** [comment] 2017-04-25 09:47
> Do you mean the column name should be "BKG" (upper case)?
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-2d

Yes, that is what I mean.

> For a very quick look, I don't see where the problem is:
https://github.com/gammapy/gammapy/blob/master/gammapy/background/energy_offset_array.py

Take a look at line 649/613 in: 
https://github.com/gammapy/gammapy/blob/master/gammapy/background/models.py

> Could you please make a "magic" folder in
https://github.com/gammapy/gammapy-extra/tree/master/test_datasets
and put example IRF files for one run there?

Yes. I will just set all values to 1, so no-one can be even potentially bothered...

**Comment by cdeil** [comment] 2017-04-25 10:00
OK, I see. My suggestion would be to just support both keys on read here to make it work for you:
https://github.com/gammapy/gammapy/blob/master/gammapy/background/models.py#L649
(and to add a regression test with a properly formatted file)
As I said, we have to rewrite that class anyways, but for now, it's good to make it work.

> I will just set all values to 1, so no-one can be even potentially bothered...

If you anyways don't fill with MAGIC data, then it would be even better if you write a Python script and add an example file with the right header keys and columns to the spec:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-2d
We should do this for all formats anyways, the original idea to use real example files from HESS / MAGIC isn't a good one (I can explain why if needed).

The idea is that we then use these example files from the spec repo for tests in Gammapy (we already do this in some cases).

**Comment by TarekHC** [comment] 2017-04-25 10:05
> OK, I see. My suggestion would be to just support both keys on read here to make it work for you:
https://github.com/gammapy/gammapy/blob/master/gammapy/background/models.py#L649
(and to add a regression test with a properly formatted file)

That would be nice (although note it should be done both for the 2D and 3D!).

> If you anyways don't fill with MAGIC data, then it would be even better if you write a Python script and add an example file with the right header keys and columns to the spec:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-2d

I agree. We have the one from the effective area, so it would be very fast to do. I'll try to do it soon.

**Comment by TarekHC** [comment] 2017-04-26 14:10
> If you anyways don't fill with MAGIC data, then it would be even better if you write a Python script and add an example file with the right header keys and columns to the spec:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-2d
We should do this for all formats anyways, the original idea to use real example files from HESS / MAGIC isn't a good one (I can explain why if needed).

An example python script creating a sample background FITS file using ``BKG_2D`` and ``BKG_3D`` formats was added in:
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/85

See:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html

**Comment by cdeil** [comment] 2017-11-05 17:15
@TarekHC - In Gammapy we now have a new class [gammapy.irf.Background3D](http://docs.gammapy.org/en/latest/api/gammapy.irf.Background3D.html), and the idea is that once it's more feature-complete and well-tested, the old classes in `gammapy.background` are removed.

It can read the example file now just fine:
```
wget http://gamma-astro-data-formats.readthedocs.io/en/latest/_downloads/bkg_3d_full_example.fits
python
>>> from gammapy.irf import Background3D
>>> bkg = Background3D.read('bkg_3d_full_example.fits')
>>> print(bkg)
```
And to also support the existing files with column name "BGD" we support that as well.

I'm keeping this issue open for now, but I'm not sure there's any concrete action item left here concerning column names. The larger task of adding a `gammapy.irf.Background2D` and removing the old classes in `gammapy.background` is still open, but I'm not sure if keeping this issue open helps. For now I'm moving this to the v0.8 milestone.

**Comment by TarekHC** [comment] 2017-11-05 23:29
Well, the main problem of the issue is now solved, so from my point of view, you can close it. 

Maybe we can create a new issue explicitly requesting for the addition of Background2D?

**Comment by cdeil** [comment] 2018-01-29 09:10
I'm closing this old issue now. There's a reminder about the 2D background class here:
https://github.com/gammapy/gammapy/issues/947#issuecomment-361182360

@TarekHC - Thanks for checking the formats in detail!

**Closed by cdeil** 2018-01-29 09:10 UTC
Labels: bug, cleanup
