### ISSUE TITLE
Energy ranges used by SpectrumFit

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1224] opened 2017-11-30 09:16 UTC
There has been a report by @ctrichard (discussed [here](https://groups.google.com/forum/#!topic/gammapy/SPYVIvL_I6o )) and also by @cosimoNigro (discussed [here](https://github.com/gammasky/joint-crab/pull/27)) that they see an issue with the energy ranges used by `SpectrumFit`. Specifically there is the question whether for for each run the appropriate energy range is applied (desired behaviour), or whether the safe energy range from the first run in the `SpectrumObservationList` is applied to all runs (that would be a bug).

@joleroi or @lmohrmann - If you have any info on this, please comment.

I'll try to poke around a bit to understand when energy ranges get applied where, and develop a minimal test case today.

**Comment by cdeil** [comment] 2017-12-04 16:58
@joleroi - This is the last blocker for v0.7. Do you have time to make a test case with two runs and check how energy ranges are handled by SpectrumFit this week? If no, please assign to me and I'll do it before releasing v0.7.

**Comment by cosimoNigro** [comment] 2017-12-05 12:26
Hello, 
I took a look and did some tests, maybe this info can help.
Both the functions `_apply_fit_range` and `true_fit_range` look ok to me
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/fit.py#L139
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/fit.py#L123
* the first return a list of boolean arrays for each event observations with the bins to be used,
* the second returns a list of the extremes of the energy ranges to be used.

I suspect that the problem is here
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/fit.py#L371
the sherpa wrapper is initialized with the binning of the first event list, this is maybe why in 
https://github.com/gammasky/joint-crab/pull/27
we see that it keeps returning the energy range of the first event list (Fermi) ignoring the others (MAGIC or HESS). 
Hope it can help.

**Comment by joleroi** [comment] 2017-12-19 08:44
> I suspect that the problem is here
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/fit.py#L371

Just to comment on that: As stated in the line below the Sherpa data object is not used in the fit, so I can't image that this line causes any trouble. We will, however, see how the discussion in #1236 develops and maybe come back to this.

**Comment by cosimoNigro** [comment] 2017-12-20 07:40
Thanks for the explanation, with PR #1236 by @joleroi this is clarified and a test is also added.
This Issue can be closed.

**Comment by joleroi** [comment] 2017-12-20 08:50
> There has been a report by @ctrichard (discussed here) 

this is still not checked/resolved so let's keep this issue open

**Comment by cosimoNigro** [comment] 2018-02-07 16:12
Hello @joleroi, @cdeil, @registerrier 
I think the issue is still there, I am pretty convinced that it `SpectrumFit` takes as fit range the extremes of the first observation lists. 
To trigger the issue you can use the OGIP files in the `joint-crab` repo, you all have access. 
I am sorry if somebody does not have access but I could not figure out a better example. 
Code to trigger the issue follow, I realized the range was ignored by printing the yaml file with the output. Now I think it is clear that Spectrum Fit is not using the full energy range.
```python
import astropy.units as u
import yaml
from gammapy.spectrum import SpectrumObservation, SpectrumObservationList, SpectrumFit
from gammapy.spectrum.models import LogParabola

# load three observation lists with different energies
obs1 = SpectrumObservation.read('joint-crab/data/fermi/ogip-spectra/pha_obs0.fits')
obs2 = SpectrumObservation.read('joint-crab/data/magic/ogip-spectra/pha_obs5029747.fits')
obs3 = SpectrumObservation.read('joint-crab/data/hess/ogip-spectra/pha_obs23523.fits')

obs_list = SpectrumObservationList([obs1, obs2, obs3])
   
model_lp = LogParabola(
        amplitude=3.80 * 1e-11 * u.Unit('cm-2 s-1 TeV-1'),
        reference=1 * u.Unit('TeV'),
        alpha=2.47 * u.Unit(''),
        beta=0.24 * u.Unit(''),
)

# set the energy range
energy_range = [0.03, 30] * u.TeV

fit = SpectrumFit(obs_list=obs_list, model=model_lp, fit_range=energy_range)
fit.run()

print(fit.result[0])

# write a yaml file 
fit._write_result('./')

with open('fit_result_LogParabola.yaml', 'r') as yaml_dict:
        dict_model = yaml.load(yaml_dict)

e_min = dict_model['fit_range']['min'] * u.Unit(dict_model['fit_range']['unit'])
e_max = dict_model['fit_range']['max'] * u.Unit(dict_model['fit_range']['unit'])

print('minimum energy used: ', e_min)
print('maximum energy used: ', e_max)

# these are exactly the lo and hi  thresholds of the first observation in the list
print('obs1.lo_threshold: ', obs1.lo_threshold)
print('obs1.hi_threshold: ', obs1.hi_threshold)
```
You can already see in the output that the range you selected is ignored
```
Fit result info 
--------------- 
Model: LogParabola

Parameters: 

	   name     value     error         unit      min max frozen
	--------- --------- --------- --------------- --- --- ------
	amplitude 3.322e-11 1.789e-12 1 / (cm2 s TeV) nan nan  False
	reference 1.000e+00 0.000e+00             TeV nan nan   True
	    alpha 2.641e+00 5.493e-02                 nan nan  False
	     beta 1.286e-01 1.792e-02                 nan nan  False

Covariance: 

	name/name amplitude   alpha     beta  
	--------- --------- --------- --------
	amplitude   3.2e-24 -3.39e-14 3.74e-16
	    alpha -3.39e-14   0.00302 0.000887
	     beta  3.74e-16  0.000887 0.000321 

Statistic: 12.254 (wstat)
Fit Range: [  3.00000000e+07   2.00000000e+09] keV
```
He is using as a fit range `obs.lo_threshold` and  `obs1.hi_threshold` that in turn, if no explicit threshold is given, are taken from `obs1.e_reco`.

This is why I suspected the problem was coming from this line
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/fit.py#L371
but maybe I am wrong.
To set a fit range in sherpa something like 
http://cxc.harvard.edu/sherpa/ahelp/notice.html
shall be used....

If there is time for this in the coding sprint I can devote some hours to help.

Thanks

**Comment by joleroi** [comment] 2018-03-20 12:49
@cosimoNigro we clarified this when you were in HD, right?
``fit.result[0]`` is the result for the first observation, so the fit range is naturally the one which the first observation is fitted in. Ok, to close this?

**Comment by cdeil** [comment] 2018-03-20 16:18
Most people are confused by energy ranges used. Probably log printout or docs should be improved, no?

**Comment by joleroi** [comment] 2018-03-22 09:53
Done in https://github.com/gammapy/gammapy/commit/2f063309f8f368ee542fe538f61ede4fb52e6644

**Closed by joleroi** 2018-03-22 09:53 UTC
Labels: bug
