### ISSUE TITLE
Class attributes names should be checked at setting time

### ISSUE THREAD

**Issue by HealthyPear** [gammapy/gammapy#5540] opened 2024-11-05 10:46 UTC
**Is your feature request related to a problem? Please describe.**

After creating a SpectrumDataset instance if one does by mistake 

`spectrum_dataset.model = bla `

instead of 

`spectrum_dataset.models = bla` 

_gammapy_ does not issue any error, instead lets the user go on with the analysis and obtain incorrect results.

(yes, there is the documentation, but in this case the absence of an error message does not help the user pinpoint _where_ to go in the docs to check what's wrong)

**Describe the solution you'd like**

There should be a check (throughout all _gammapy_, not only this example case) where if a user tries to set or get a non-existent class attribute a validation error should be raised.

I see that _gammapy_ uses _pydantic_ here and there, so I guess this could be the easiest solution, but I never used it myself.

**Comment by adonath** [comment] 2024-11-08 17:07
Thanks @HealthyPear, I am closing this as a duplicate of https://github.com/gammapy/gammapy/issues/3225. Please comment there if you have additional thoughts.

**Closed by adonath** 2024-11-08 17:07 UTC
Labels: feature-request
