### ISSUE TITLE
Bad flux points possibly related to new EdispMap

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy#2668] opened 2019-12-05 11:16 UTC
**Gammapy version**
v0.15

**Bug description**
In 1dc validation, I produced flux points for casA & J1702 regularly and a strange feature appeared ~after Granada.
![CasA flux points with v0.15](https://raw.githubusercontent.com/gammapy/gammapy-benchmarks/master/validation/cta-1dc/cas_a/cas_a_fluxpoints.png)

The 2 last points are way above the reference spectrum and this feature was not seen before Granada (see older plots [here](https://github.com/gammapy/gammapy-benchmarks/blob/3f59ef1917e09fb68d988496547d91946d9c38d3/validation/cta-1dc/results/CasA_3d_fluxpoints.png) )

The symptom is that Minuit failed to converge in fluxpoints producing Nan flux points.

```
INFO:gammapy.analysis.core:Calculating flux points.
WARNING:gammapy.spectrum.flux_point:Fit failed for flux point between 15.744 TeV and 19.438 TeV, setting NaN.
       e_ref               ref_flux                 dnde                 dnde_ul                dnde_err        is_ul
        TeV              1 / (cm2 s)          1 / (cm2 s TeV)        1 / (cm2 s TeV)        1 / (cm2 s TeV)
------------------- ---------------------- ---------------------- ---------------------- ---------------------- -----
[...]
  6.843836142250355 2.4729921665087526e-14  9.750805698222948e-15 1.7086356598729693e-14 3.0298805969022534e-15 False
  9.936599900604318 6.2249770555978826e-15 2.5098633614650116e-15 1.2219958435197287e-14 2.7696222834435086e-15  True
 12.740797213004074  4.003408762173673e-15 1.4097179828349936e-13  6.510260389376602e-13 1.4509344595027408e-13 False
  16.33636407288775 2.5746732194998767e-15  6.288870717328843e-13  6.288870726217841e-13  4.489517804691946e-17 False
 20.946632040383328 1.6558244688485395e-15                    nan                    nan                    nan  True
  30.41251975124424  1.749749277156276e-15                    nan                    nan                    nan False
 44.156089429396175 4.4044414094217623e-16                    nan                    nan                    nan False
```

**To Reproduce**
Code to reproduce is available in the validation repo [here](https://github.com/gammapy/gammapy-benchmarks/tree/master/validation/cta-1dc).

We discussed this issue with @registerrier yesterday and I think this could be related to the new `Edispmap` feature.
When quickly trying, it seemed that the integral in one E_true bin was not 1.
Not yet sure whether this is the cause of the problem but this is a possible clue.

**Comment by adonath** [comment] 2019-12-05 12:26
Thanks @fabiopintore for reporting this. 

Note that the use of the `EDispMap` under the hood in the `Analysis` class was already [in place](https://github.com/gammapy/gammapy/blob/v0.14/gammapy/scripts/analysis.py#L295) since v0.14. But there we just extracted the `EnergyDispersion` at the center of the map. The difference in v0.15 is now that the energy dispersion is extracted at the position of the model component. 

I noticed that the energy binning is different in the plots. Do you see the same behaviour, when changing back to the wider energy binning in the previous plot?

**Comment by facero** [comment] 2019-12-05 12:34
![cas_a_fluxpoints](https://user-images.githubusercontent.com/8652898/70235658-a5422c80-1763-11ea-89c8-3121a686ce5f.png)
This is the plot with 10 bins as before and there is still an issue ...
I also tried to modify the center of geom to test a pixel edge effect and it does not change the points.

**Comment by facero** [comment] 2019-12-05 12:49
> Thanks @fabiopintore for reporting this.
> 
You quoted the wrong fabio by the way ;-)

**Comment by adonath** [comment] 2019-12-05 13:18
> You quoted the wrong fabio by the way ;-)

Oops...sorry, I guess he cannot help us here...;-)

Indeed the issue remains, I'll checkout the latest `gammapy-benchmark` now and try to reproduce it.

**Comment by adonath** [comment] 2019-12-05 16:30
I could reproduce the issue an investigated the energy dispersion matrix:
![Screenshot 2019-12-05 at 14 58 49](https://user-images.githubusercontent.com/3715928/70253414-75a31c80-1783-11ea-9007-2e060c559f5a.png)

Taking a look at the axes you can see the issue is a completely different one: the true energy axis goes only up to `10 TeV`.  After the application of the matrix, the upper energy bins of the predicted counts are empty, that's why the fit fails. The issue was introduced by setting a non-reasonable default for the true energy axis in our config: https://github.com/gammapy/gammapy/blob/master/gammapy/analysis/config.py#L98

But this means it's also easy to fix. Once you specify a true energy binning in your config the issue should be gone. Here's the yaml example:
```
    geom:
        wcs:
            skydir: {frame: icrs, lon: 83.633 deg, lat: 22.014 deg}
            binsize: 0.1 deg
            fov: {width: 7 deg, height: 5 deg}
            binsize_irf: 0.1 deg
        selection:
            offset_max: 2.5 deg
        axes:
            energy: {min: 0.1 TeV, max: 10 TeV, nbins: 30}
            energy_true: {min: 0.1 TeV, max: 10 TeV, nbins: 30}
```
Somehow this non-reasonable default choice went through the review, without somebody noticing it.

First I was wondering why the Gammapy fit would not fail with an error, because the map geometries of counts and exposure are not aligned, but after application of the edisp the axes are aligned of course. I think we should definitely change the default values in the `AnalysisConfig`, but maybe we should also check somewhere for the energy bounds of the true energy bins...?

**Comment by facero** [comment] 2019-12-06 08:53
Thanks, this seems to fix the issue with the flux points. 
Just to be sure, would be good to double check that the Edispmap integral in one E_true bin is 1.
We checked really quickly and would be good to verify this before closing the issue.
![cas_a_fluxpoints](https://user-images.githubusercontent.com/8652898/70309544-12aa9780-180e-11ea-935b-f698e116ecf8.png)

**Comment by adonath** [comment] 2020-01-30 18:18
The self consistency of the EDispMap handling is now verified in https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/event-sampling/checks/edisp_check.ipynb.

**Comment by adonath** [comment] 2020-02-28 14:31
I'm closing this as a duplicate of #2669.

**Closed by adonath** 2020-02-28 14:31 UTC
Labels: bug
