### ISSUE TITLE
Axes transposed between maps and geom

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1462] opened 2018-07-09 19:13 UTC
It seems that the shape of the non-spatial axes are transposed between the geom object and the map object.

eg: see lines 14 and 15 of https://github.com/gammapy/gammapy-extra/blob/master/notebooks/intro_maps.ipynb

ie, `geom4d.shape` gives (10, 3), while `map4d.data.shape` gives (3, 10, 300, 300)

@woodmd,  can you comment why this is so?

**Comment by woodmd** [comment] 2018-07-10 02:03
Yes this is by design.  See #1180 for a detailed explanation of why the `data` axes are transposed.

**Comment by AtreyeeS** [comment] 2018-07-10 13:09
Thanks @woodmd !

**Comment by cdeil** [comment] 2018-07-18 06:52
@AtreyeeS - I'm putting this on the v0.8 milestone and assigning to you.

Please update the map intro notebook with an explanation about axis order, and change the example so that the spatial axis have different length. E.g. 200 x 100 pixels or anything you like, as long as in printouts of `shape` the order of the axes is visible as `(200, 100)` or `(100, 200)`, instead of the current `(300, 300)`.

**Comment by cdeil** [comment] 2018-07-27 10:48
@AtreyeeS - This is the only issue left for you under the v0.8 milestone.
Do you still have time to do this update to the notebook before you go on vacation?
If no - please assign to me and I'll do this in the next days, no problem.

**Comment by AtreyeeS** [comment] 2018-07-27 11:06
Hello, I wrote a few lines explaining this in the `intro_maps` notebook in the `Exploring maps` section (after input cell 15): https://github.com/gammapy/gammapy-extra/blob/master/notebooks/intro_maps.ipynb

Do you want me to put in some more details?

**Comment by cdeil** [comment] 2018-07-27 11:07
Thanks for doing this!
Closing issue.

**Closed by cdeil** 2018-07-27 11:07 UTC
Labels: question
